//$file${.::Cores_Project::CPU1::qm_files::main_qm.h} vvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: main_model.qm
// File:  ${.::Cores_Project::CPU1::qm_files::main_qm.h}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Cores_Project::CPU1::qm_files::main_qm.h} ^^^^^^^^^^^^^^^^^^^^^
#ifndef MAIN_QM_H_
#define MAIN_QM_H_

#include "ipc_config.h"
#include "qpc.h"
#include "bsp_basic.h"

//================================================
//====================Signals=====================
//================================================

//$declare${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::Signals::com_signals_ipc} ........................................
enum com_signals_ipc {
    //Index Signals Here
    COM_SIG_IPC_CAN_SEND_MSG,
    COM_SIG_IPC_MAX,
};

//${Shared::Signals::com_signals_can} ........................................
enum com_signals_can {
    COM_SIG_CAN_MAX,
};

//${Shared::Event_Types::OC_Evt} .............................................
typedef struct {
// protected:
    QEvt super;

// public:
    uint16_t ID;
} OC_Evt;

//${Shared::Event_Types::OC_TimeEvt} .........................................
typedef struct {
// protected:
    QTimeEvt super;

// public:
    uint16_t ID;
} OC_TimeEvt;

//${Shared::Event_Types::OC_IPC_types::struct} ...............................
typedef struct {
    uint16_t com_ipc_sig;
    uint16_t payload[BSP_IPC_MAX_PAYLOAD_SIZE-2];
}oc_ipc_msg_t;

//${Shared::Event_Types::OC_IPC_types::OC_Evt_IPC_Message_t} .................
typedef struct {
// protected:
    OC_Evt super;

// public:
    oc_ipc_msg_t msg;
} OC_Evt_IPC_Message_t;

//${Shared::Macros::OC_IPC_CMD_REMOTE_RESET} .................................
#define OC_IPC_CMD_REMOTE_RESET 0


//${Shared::Macros::OC_IPC_CMD_RESET_COMPLETE} ...............................
#define OC_IPC_CMD_RESET_COMPLETE 1
//$enddecl${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${OCs::Signals} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${OCs::Signals::OC_IPC_SIGNALS} ............................................
#define OC_IPC_SIGNALS \
    IPC_RECEIVE_MSG_SIG,\
    IPC_SEND_MSG_SIG,\
    IPC_FULL_BUS_SIG,\
    IPC_RESET_CH_SIG,\
    IPC_REMOTE_RESET_SIG,\
    IPC_RESET_COMPLETE_SIG

//${OCs::Signals::OC_CAN_SIGNALS} ............................................
#define OC_CAN_SIGNALS \
    CAN_RECEIVE_MSG_SIG,\
    CAN_SEND_MSG_SIG,\
    CAN_PASSIVE_ERROR_SIG,\
    CAN_BUS_OFF_SIG,\
    CAN_ERROR_CLEAR_SIG
//$enddecl${OCs::Signals} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${CPU1::Signals} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CPU1::Signals::private_signals} ..........................................
enum private_signals {
// Publish Subscribe Signals
    TIMEOUT_SIG = Q_USER_SIG,

    // - Only PRIVATE

    MAX_PUB_SIG,

    // COMMON Signals
    RUNNING_QF_SIG,
    INIT_COMPLETE_SIG,

    //FSBB Signals
    PRECHARGE_START_SIG,
    PRECHARGE_FINISH_SIG,
    START_CONTROL_SIG,
    STOP_CONTROL_SIG,
    IL_0_SIG,
    RESET_SIG,
    SET_FAULT_SIG,
    CLEAR_FAULT_SIG,

    // CAN OC Signals
    OC_CAN_SIGNALS,

    // IPC OC Signals
    OC_IPC_SIGNALS,


    MAX_PRIVATE_SIG,
};

//${CPU1::Signals::struct} ...................................................
typedef struct {
    uint16_t const sig_id;
    QActive * const p_ao;
}com_ipc_tag_t;

//${CPU1::Signals::com_signals_ipc_table[COM_SIG_IP~} ........................
extern QActive * const com_signals_ipc_table[COM_SIG_IPC_MAX];
//$enddecl${CPU1::Signals} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//================================================
//===================Priorities===================
//================================================

//$declare${CPU1::ao_priority} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CPU1::ao_priority} .......................................................
enum ao_priority {
    // Priority in ascendance order
    IDLE_TASK=0U,
    AO_COMMUNICATION_PRIO,
    AO_FSBB_CONTROL_PRIO,
};
//$enddecl${CPU1::ao_priority} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//================================================
//=================Active-Objects=================
//================================================

// AO_FSBB_Control
//$declare${CPU1::AOs::AO_FSBB_Control::globals} vvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CPU1::AOs::AO_FSBB_Control::globals::p_ao_fsbb_control} ..................
extern QActive * const p_ao_fsbb_control;

//${CPU1::AOs::AO_FSBB_Control::globals::ao_fsbb_control_ctor} ...............
void ao_fsbb_control_ctor(const QActive  * const pAO);
//$enddecl${CPU1::AOs::AO_FSBB_Control::globals} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// AO_Communication
//$declare${CPU1::AOs::AO_Communication::globals} vvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CPU1::AOs::AO_Communication::globals::p_ao_communication} ................
extern QActive * const p_ao_communication;

//${CPU1::AOs::AO_Communication::globals::ao_communication_ctor} .............
void ao_communication_ctor(const QActive  * const pAO);
//$enddecl${CPU1::AOs::AO_Communication::globals} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//================================================
//=============Orthogonal-Components==============
//================================================

//$declare${CPU1::OC_enum} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CPU1::OC_enum::IPC::ipc_named} ...........................................
enum ipc_named {
    OC_IPC_CPU1_CPU2_ID,
    OC_IPC_CPU1_CM_ID,
    OC_IPC_NUM_OF_INST,
};

//${CPU1::OC_enum::CAN::can_named} ...........................................
enum can_named {
    OC_CAN_CANB_ID,
    OC_CAN_NUM_OF_INST,
};
//$enddecl${CPU1::OC_enum} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//================================================
//================Immutable-Events================
//================================================

//$declare${CPU1::Immutable_Events} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CPU1::Immutable_Events::General::im_evt_running_qf} ......................
extern QEvt const im_evt_running_qf;

//${CPU1::Immutable_Events::General::im_evt_init_complete} ...................
extern QEvt const im_evt_init_complete;

//${CPU1::Immutable_Events::FSBB::im_evt_precharge_start} ....................
extern QEvt const im_evt_precharge_start;

//${CPU1::Immutable_Events::FSBB::im_evt_precharge_finish} ...................
extern QEvt const im_evt_precharge_finish;

//${CPU1::Immutable_Events::FSBB::im_evt_start_control} ......................
extern QEvt const im_evt_start_control;

//${CPU1::Immutable_Events::FSBB::im_evt_stop_control} .......................
extern QEvt const im_evt_stop_control;

//${CPU1::Immutable_Events::FSBB::im_evt_il_0} ...............................
extern QEvt const im_evt_il_0;

//${CPU1::Immutable_Events::FSBB::im_evt_reset} ..............................
extern QEvt const im_evt_reset;

//${CPU1::Immutable_Events::Communication::im_evt_ipc_receive_msg[OC_IPC_NU~}
extern OC_Evt const im_evt_ipc_receive_msg[OC_IPC_NUM_OF_INST];

//${CPU1::Immutable_Events::Communication::im_evt_ipc_send_msg[OC_IPC_NUM_O~}
extern OC_Evt const im_evt_ipc_send_msg[OC_IPC_NUM_OF_INST];

//${CPU1::Immutable_Events::Communication::im_evt_ipc_full_bus[OC_IPC_NUM_O~}
extern OC_Evt const im_evt_ipc_full_bus[OC_IPC_NUM_OF_INST];

//${CPU1::Immutable_Events::Communication::im_evt_ipc_reset_ch[OC_IPC_NUM_O~}
extern OC_Evt const im_evt_ipc_reset_ch[OC_IPC_NUM_OF_INST];

//${CPU1::Immutable_Events::Communication::im_evt_ipc_reset_complete[OC_IPC~}
extern OC_Evt const im_evt_ipc_reset_complete[OC_IPC_NUM_OF_INST];

//${CPU1::Immutable_Events::Communication::im_evt_ipc_remote_reset[OC_IPC_N~}
extern OC_Evt const im_evt_ipc_remote_reset[OC_IPC_NUM_OF_INST];
//$enddecl${CPU1::Immutable_Events} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif // MAIN_QM_H_
