//$file${.::Cores_Project::CPU1::qm_files::main_qm.c} vvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: main_model.qm
// File:  ${.::Cores_Project::CPU1::qm_files::main_qm.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Cores_Project::CPU1::qm_files::main_qm.c} ^^^^^^^^^^^^^^^^^^^^^
#include "main_qm.h"

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//$enddef${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${CPU1::Immutable_Events} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CPU1::Immutable_Events::General::im_evt_running_qf} ......................
QEvt const im_evt_running_qf = QEVT_INITIALIZER(RUNNING_QF_SIG);

//${CPU1::Immutable_Events::General::im_evt_init_complete} ...................
QEvt const im_evt_init_complete = QEVT_INITIALIZER(INIT_COMPLETE_SIG);

//${CPU1::Immutable_Events::FSBB::im_evt_precharge_start} ....................
QEvt const im_evt_precharge_start = QEVT_INITIALIZER(PRECHARGE_START_SIG);

//${CPU1::Immutable_Events::FSBB::im_evt_precharge_finish} ...................
QEvt const im_evt_precharge_finish = QEVT_INITIALIZER(PRECHARGE_FINISH_SIG);

//${CPU1::Immutable_Events::FSBB::im_evt_start_control} ......................
QEvt const im_evt_start_control = QEVT_INITIALIZER(START_CONTROL_SIG);

//${CPU1::Immutable_Events::FSBB::im_evt_stop_control} .......................
QEvt const im_evt_stop_control = QEVT_INITIALIZER(STOP_CONTROL_SIG);

//${CPU1::Immutable_Events::FSBB::im_evt_reset} ..............................
QEvt const im_evt_reset = QEVT_INITIALIZER(RESET_SIG);

//${CPU1::Immutable_Events::FSBB::im_evt_clear_fault} ........................
QEvt const im_evt_clear_fault = QEVT_INITIALIZER(CLEAR_FAULT_SIG);

//${CPU1::Immutable_Events::FSBB::im_evt_change_setpoint} ....................
QEvt const im_evt_change_setpoint = QEVT_INITIALIZER(CHANGE_SETPOINT_SIG);

//${CPU1::Immutable_Events::FSBB::im_evt_skiip_1_heart_beat} .................
QEvt const im_evt_skiip_1_heart_beat = QEVT_INITIALIZER(SKIIP1_HEART_BEAT_SIG);

//${CPU1::Immutable_Events::FSBB::im_evt_skiip_2_heart_beat} .................
QEvt const im_evt_skiip_2_heart_beat = QEVT_INITIALIZER(SKIIP2_HEART_BEAT_SIG);

//${CPU1::Immutable_Events::FSBB::im_evt_update_measure} .....................
QEvt const im_evt_update_measure = QEVT_INITIALIZER(UPDATE_MEASURE_SIG);

//${CPU1::Immutable_Events::Communication::IPC::im_evt_ipc_reset_ch[OC_IPC_NUM_O~}
OC_Evt const im_evt_ipc_reset_ch[OC_IPC_NUM_OF_INST] ={
#ifdef DUALCORE
    [OC_IPC_CPU1_CPU2_ID] = {
        .super = QEVT_INITIALIZER(IPC_RESET_CH_SIG),
        .ID = OC_IPC_CPU1_CPU2_ID,
    },
#endif
    [OC_IPC_CPU1_CM_ID] = {
        .super = QEVT_INITIALIZER(IPC_RESET_CH_SIG),
        .ID = OC_IPC_CPU1_CM_ID,
    }
};

//${CPU1::Immutable_Events::Communication::IPC::im_evt_ipc_reset_complete[OC_IPC~}
OC_Evt const im_evt_ipc_reset_complete[OC_IPC_NUM_OF_INST] ={
#ifdef DUALCORE
    [OC_IPC_CPU1_CPU2_ID] = {
        .super = QEVT_INITIALIZER(IPC_RESET_COMPLETE_SIG),
        .ID = OC_IPC_CPU1_CPU2_ID,
    },
#endif
    [OC_IPC_CPU1_CM_ID] = {
        .super = QEVT_INITIALIZER(IPC_RESET_COMPLETE_SIG),
        .ID = OC_IPC_CPU1_CM_ID,
    }
};

//${CPU1::Immutable_Events::Communication::IPC::im_evt_ipc_full_bus[OC_IPC_NUM_O~}
OC_Evt const im_evt_ipc_full_bus[OC_IPC_NUM_OF_INST] ={
#ifdef DUALCORE
    [OC_IPC_CPU1_CPU2_ID] = {
        .super = QEVT_INITIALIZER(IPC_FULL_BUS_SIG),
        .ID = OC_IPC_CPU1_CPU2_ID,
    },
#endif
    [OC_IPC_CPU1_CM_ID] = {
        .super = QEVT_INITIALIZER(IPC_FULL_BUS_SIG),
        .ID = OC_IPC_CPU1_CM_ID,
    }
};

//${CPU1::Immutable_Events::Communication::IPC::im_evt_ipc_remote_reset[OC_IPC_N~}
OC_Evt const im_evt_ipc_remote_reset[OC_IPC_NUM_OF_INST] ={
#ifdef DUALCORE
    [OC_IPC_CPU1_CPU2_ID] = {
        .super = QEVT_INITIALIZER(IPC_REMOTE_RESET_SIG),
        .ID = OC_IPC_CPU1_CPU2_ID,
    },
#endif
    [OC_IPC_CPU1_CM_ID] = {
        .super = QEVT_INITIALIZER(IPC_REMOTE_RESET_SIG),
        .ID = OC_IPC_CPU1_CM_ID,
    }
};

//${CPU1::Immutable_Events::Communication::IPC::im_evt_ipc_send_msg[OC_IPC_NUM_O~}
OC_Evt const im_evt_ipc_send_msg[OC_IPC_NUM_OF_INST] ={
#ifdef DUALCORE
    [OC_IPC_CPU1_CPU2_ID] = {
        .super = QEVT_INITIALIZER(IPC_SEND_MSG_SIG),
        .ID = OC_IPC_CPU1_CPU2_ID,
    },
#endif
    [OC_IPC_CPU1_CM_ID] = {
        .super = QEVT_INITIALIZER(IPC_SEND_MSG_SIG),
        .ID = OC_IPC_CPU1_CM_ID,
    }
};

//${CPU1::Immutable_Events::Communication::IPC::im_evt_ipc_receive_msg[OC_IPC_NU~}
OC_Evt const im_evt_ipc_receive_msg[OC_IPC_NUM_OF_INST] ={
#ifdef DUALCORE
    [OC_IPC_CPU1_CPU2_ID] = {
        .super = QEVT_INITIALIZER(IPC_RECEIVE_MSG_SIG),
        .ID = OC_IPC_CPU1_CPU2_ID,
    },
#endif
    [OC_IPC_CPU1_CM_ID] = {
        .super = QEVT_INITIALIZER(IPC_RECEIVE_MSG_SIG),
        .ID = OC_IPC_CPU1_CM_ID,
    }
};

//${CPU1::Immutable_Events::Communication::CAN::im_evt_can_send_msg[OC_CAN_NUM_O~}
OC_Evt const im_evt_can_send_msg[OC_CAN_NUM_OF_INST] ={
    [OC_CAN_CAN_SKIIP_ID] = {
        .super = QEVT_INITIALIZER(CAN_SEND_MSG_SIG),
        .ID = OC_CAN_CAN_SKIIP_ID,
    },
};
//$enddef${CPU1::Immutable_Events} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${CPU1::Signals} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CPU1::Signals::com_signals_ipc_cpu2_cpu1[COM_SI~} ........................
com_tag_t com_signals_ipc_cpu2_cpu1[COM_SIG_IPC_CPU2_CPU1_MAX] ={
};

//${CPU1::Signals::com_signals_ipc_cm_cpu1[COM_SIG_~} ........................
com_tag_t com_signals_ipc_cm_cpu1[COM_SIG_IPC_CM_CPU1_MAX] ={
    [COM_SIG_IPC_CM_CPU1_CONTROL_START] = {
        .p_ao = &p_ao_fsbb_control,
        .im_evt = &im_evt_start_control,
    },
    [COM_SIG_IPC_CM_CPU1_CONTROL_STOP] = {
        .p_ao = &p_ao_fsbb_control,
        .im_evt = &im_evt_stop_control,
    },
    [COM_SIG_IPC_CM_CPU1_EMERGENCY_SHUTDOWN] = {
        .p_ao = &p_ao_fsbb_control,
        .im_evt = &im_evt_start_control,
    },
    [COM_SIG_IPC_CM_CPU1_PRECHARGE_START] = {
        .p_ao = &p_ao_fsbb_control,
        .im_evt = &im_evt_precharge_start,
    },
    [COM_SIG_IPC_CM_CPU1_RESET] = {
        .p_ao = &p_ao_fsbb_control,
        .im_evt = &im_evt_reset,
    },
    [COM_SIG_IPC_CM_CPU1_CLEAR_FAULT] = {
        .p_ao = &p_ao_fsbb_control,
        .im_evt = &im_evt_clear_fault,
    },
    [COM_SIG_IPC_CM_CPU1_CHANGE_SETPOINT] = {
        .p_ao = &p_ao_fsbb_control,
        .im_evt = &im_evt_change_setpoint,
    },
};

//${CPU1::Signals::com_signals_can_skiip[COM_SIG_CA~} ........................
const com_tag_t com_signals_can_skiip[COM_SIG_CAN_SKIIP_MAX] ={
    [COM_SIG_CAN_SKIIP_1_HEART_BEAT] = {
        .p_ao = &p_ao_fsbb_control,
        .im_evt = &im_evt_skiip_1_heart_beat,
    },
    [COM_SIG_CAN_SKIIP_2_HEART_BEAT] = {
        .p_ao = &p_ao_fsbb_control,
        .im_evt = &im_evt_skiip_2_heart_beat,
    },
    [COM_SIG_CAN_SKIIP_UPDATE_MEASURE] = {
        .p_ao = &p_ao_fsbb_control,
        .im_evt = &im_evt_update_measure,
    },
};

//$enddef${CPU1::Signals} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
