/************************************************************/
// Automatically generated C header file from CAN DBC file
// Source file name: modulink.dbc
// Date created: 2024-08-28
/************************************************************/


#ifndef MODULINK_DBC_H_
#define MODULINK_DBC_H_
typedef struct{
    uint64_t byte_0:8;
    uint64_t byte_1:8;
    uint64_t byte_2:8;
    uint64_t byte_3:8;
    uint64_t byte_4:8;
    uint64_t byte_5:8;
    uint64_t byte_6:8;
    uint64_t byte_7:8;
}Can_Bytes_Data_t;

typedef union{
    uint64_t         full_payload;
    Can_Bytes_Data_t byte_data;
}Can_Payload_t;


/************************************************************/
//====================Messages Proprieties====================
/************************************************************/



#define MODULINK_CAN_MSG_RECEIVE_ID_EXT 0x00ff8300
#define MODULINK_CAN_MSG_RECEIVE_MASK_EXT 0x1e000300



/************************************************************/
// Message: IHM_COMMANDS_1_VPU
/************************************************************/
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_FRAME_ID 0xff8000

// Signal: IHM_CONTROL_START_VPU
#define MODULINK_CAN_SIG_IHM_CONTROL_START_VPU MODULINK_CAN_SIG_IHM_CONTROL_START_VPU
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_CAN_SIG_IHM_CONTROL_START_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_START_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_START_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_START_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_START_VPU_MAXIMUM 1
// Named Values to Signal: IHM_CONTROL_START_VPU
#define MODULINK_CAN_VALUE_NO MODULINK_CAN_VALUE_NO
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_START_VPU_MODULINK_CAN_VALUE_NO 0
#define MODULINK_CAN_VALUE_YES MODULINK_CAN_VALUE_YES
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_START_VPU_MODULINK_CAN_VALUE_YES 1
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_START_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 0 & 0b00000001 )

#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_START_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b11111110);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b00000001 ) << 0); \


// Signal: IHM_CONTROL_STOP_VPU
#define MODULINK_CAN_SIG_IHM_CONTROL_STOP_VPU MODULINK_CAN_SIG_IHM_CONTROL_STOP_VPU
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_CAN_SIG_IHM_CONTROL_STOP_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_STOP_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_STOP_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_STOP_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_STOP_VPU_MAXIMUM 1
// Named Values to Signal: IHM_CONTROL_STOP_VPU
#define MODULINK_CAN_VALUE_NO MODULINK_CAN_VALUE_NO
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_STOP_VPU_MODULINK_CAN_VALUE_NO 0
#define MODULINK_CAN_VALUE_YES MODULINK_CAN_VALUE_YES
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_STOP_VPU_MODULINK_CAN_VALUE_YES 1
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_STOP_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 1 & 0b00000001 )

#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CONTROL_STOP_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b11111101);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b00000001 ) << 1); \


// Signal: IHM_EMERGENCY_SHUTDOWN_VPU
#define MODULINK_CAN_SIG_IHM_EMERGENCY_SHUTDOWN_VPU MODULINK_CAN_SIG_IHM_EMERGENCY_SHUTDOWN_VPU
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_CAN_SIG_IHM_EMERGENCY_SHUTDOWN_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_EMERGENCY_SHUTDOWN_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_EMERGENCY_SHUTDOWN_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_EMERGENCY_SHUTDOWN_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_EMERGENCY_SHUTDOWN_VPU_MAXIMUM 1
// Named Values to Signal: IHM_EMERGENCY_SHUTDOWN_VPU
#define MODULINK_CAN_VALUE_NO MODULINK_CAN_VALUE_NO
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_EMERGENCY_SHUTDOWN_VPU_MODULINK_CAN_VALUE_NO 0
#define MODULINK_CAN_VALUE_YES MODULINK_CAN_VALUE_YES
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_EMERGENCY_SHUTDOWN_VPU_MODULINK_CAN_VALUE_YES 1
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_EMERGENCY_SHUTDOWN_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 2 & 0b00000001 )

#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_EMERGENCY_SHUTDOWN_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b11111011);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b00000001 ) << 2); \


// Signal: IHM_PRECHARGE_START_VPU
#define MODULINK_CAN_SIG_IHM_PRECHARGE_START_VPU MODULINK_CAN_SIG_IHM_PRECHARGE_START_VPU
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_CAN_SIG_IHM_PRECHARGE_START_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_PRECHARGE_START_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_PRECHARGE_START_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_PRECHARGE_START_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_PRECHARGE_START_VPU_MAXIMUM 1
// Named Values to Signal: IHM_PRECHARGE_START_VPU
#define MODULINK_CAN_VALUE_NO MODULINK_CAN_VALUE_NO
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_PRECHARGE_START_VPU_MODULINK_CAN_VALUE_NO 0
#define MODULINK_CAN_VALUE_YES MODULINK_CAN_VALUE_YES
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_PRECHARGE_START_VPU_MODULINK_CAN_VALUE_YES 1
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_PRECHARGE_START_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 3 & 0b00000001 )

#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_PRECHARGE_START_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b11110111);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b00000001 ) << 3); \


// Signal: IHM_CLEAR_FAULT_VPU
#define MODULINK_CAN_SIG_IHM_CLEAR_FAULT_VPU MODULINK_CAN_SIG_IHM_CLEAR_FAULT_VPU
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_CAN_SIG_IHM_CLEAR_FAULT_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CLEAR_FAULT_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CLEAR_FAULT_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CLEAR_FAULT_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CLEAR_FAULT_VPU_MAXIMUM 1
// Named Values to Signal: IHM_CLEAR_FAULT_VPU
#define MODULINK_CAN_VALUE_NO MODULINK_CAN_VALUE_NO
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CLEAR_FAULT_VPU_MODULINK_CAN_VALUE_NO 0
#define MODULINK_CAN_VALUE_YES MODULINK_CAN_VALUE_YES
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CLEAR_FAULT_VPU_MODULINK_CAN_VALUE_YES 1
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CLEAR_FAULT_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 4 & 0b00000001 )

#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_CLEAR_FAULT_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b11101111);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b00000001 ) << 4); \


// Signal: IHM_SOFT_RESET_VPU
#define MODULINK_CAN_SIG_IHM_SOFT_RESET_VPU MODULINK_CAN_SIG_IHM_SOFT_RESET_VPU
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_CAN_SIG_IHM_SOFT_RESET_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_SOFT_RESET_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_SOFT_RESET_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_SOFT_RESET_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_SOFT_RESET_VPU_MAXIMUM 1
// Named Values to Signal: IHM_SOFT_RESET_VPU
#define MODULINK_CAN_VALUE_NO MODULINK_CAN_VALUE_NO
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_SOFT_RESET_VPU_MODULINK_CAN_VALUE_NO 0
#define MODULINK_CAN_VALUE_YES MODULINK_CAN_VALUE_YES
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_SOFT_RESET_VPU_MODULINK_CAN_VALUE_YES 1
#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_SOFT_RESET_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 5 & 0b00000001 )

#define MODULINK_CAN_MSG_IHM_COMMANDS_1_VPU_MODULINK_CAN_SIG_IHM_SOFT_RESET_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b11011111);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b00000001 ) << 5); \



/************************************************************/
// Message: IHM_SETPOINTS_1_VPU
/************************************************************/
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_FRAME_ID 0xff8100

// Signal: IHM_SETPOINT_ID_VPU
#define MODULINK_CAN_SIG_IHM_SETPOINT_ID_VPU MODULINK_CAN_SIG_IHM_SETPOINT_ID_VPU
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_CAN_SIG_IHM_SETPOINT_ID_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_ID_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_ID_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_ID_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_ID_VPU_MAXIMUM 65535
// Named Values to Signal: IHM_SETPOINT_ID_VPU
#define MODULINK_CAN_VALUE_IL_CURRENT_SETPOINT MODULINK_CAN_VALUE_IL_CURRENT_SETPOINT
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_ID_VPU_MODULINK_CAN_VALUE_IL_CURRENT_SETPOINT 0
#define MODULINK_CAN_VALUE_IO_CURRENT_SETPOINT MODULINK_CAN_VALUE_IO_CURRENT_SETPOINT
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_ID_VPU_MODULINK_CAN_VALUE_IO_CURRENT_SETPOINT 1
#define MODULINK_CAN_VALUE_POWER_SETPOINT MODULINK_CAN_VALUE_POWER_SETPOINT
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_ID_VPU_MODULINK_CAN_VALUE_POWER_SETPOINT 2
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_ID_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 0 & 0b11111111 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_1) & 0b11111111) << 8 )

#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_ID_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( _RAW_VALUE >> 8) & (0b11111111); \


// Signal: IHM_SETPOINT_REQUESTED_VPU
#define MODULINK_CAN_SIG_IHM_SETPOINT_REQUESTED_VPU MODULINK_CAN_SIG_IHM_SETPOINT_REQUESTED_VPU
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_CAN_SIG_IHM_SETPOINT_REQUESTED_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_REQUESTED_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_REQUESTED_VPU_OFFSET -100
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_REQUESTED_VPU_MINIMUM -100
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_REQUESTED_VPU_MAXIMUM 100
#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_REQUESTED_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_2) >> 0 & 0b11111111 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_3) & 0b11111111) << 8 )

#define MODULINK_CAN_MSG_IHM_SETPOINTS_1_VPU_MODULINK_CAN_SIG_IHM_SETPOINT_REQUESTED_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_2 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_2 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \
_CAN_BYTES_DATA_TO_WRITE.byte_3 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_3 |= ( _RAW_VALUE >> 8) & (0b11111111); \



/************************************************************/
// Message: IHM_MANUAL_EVT_VPU
/************************************************************/
#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU
#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_FRAME_ID 0xff8200

// Signal: IHM_COM_SIG_VPU
#define MODULINK_CAN_SIG_IHM_COM_SIG_VPU MODULINK_CAN_SIG_IHM_COM_SIG_VPU
#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_CAN_SIG_IHM_COM_SIG_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_MODULINK_CAN_SIG_IHM_COM_SIG_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_MODULINK_CAN_SIG_IHM_COM_SIG_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_MODULINK_CAN_SIG_IHM_COM_SIG_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_MODULINK_CAN_SIG_IHM_COM_SIG_VPU_MAXIMUM 65535
#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_MODULINK_CAN_SIG_IHM_COM_SIG_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 0 & 0b11111111 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_1) & 0b11111111) << 8 )

#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_MODULINK_CAN_SIG_IHM_COM_SIG_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( _RAW_VALUE >> 8) & (0b11111111); \


// Signal: IHM_PAYLOAD_VPU
#define MODULINK_CAN_SIG_IHM_PAYLOAD_VPU MODULINK_CAN_SIG_IHM_PAYLOAD_VPU
#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_CAN_SIG_IHM_PAYLOAD_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_MODULINK_CAN_SIG_IHM_PAYLOAD_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_MODULINK_CAN_SIG_IHM_PAYLOAD_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_MODULINK_CAN_SIG_IHM_PAYLOAD_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_MODULINK_CAN_SIG_IHM_PAYLOAD_VPU_MAXIMUM 2
#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_MODULINK_CAN_SIG_IHM_PAYLOAD_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_2) >> 0 & 0b11111111 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_3) & 0b11111111) << 8 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_4) & 0b11111111) << 16 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_5) & 0b11111111) << 24 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_6) & 0b11111111) << 32 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_7) & 0b11111111) << 40 )

#define MODULINK_CAN_MSG_IHM_MANUAL_EVT_VPU_MODULINK_CAN_SIG_IHM_PAYLOAD_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_2 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_2 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \
_CAN_BYTES_DATA_TO_WRITE.byte_3 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_3 |= ( _RAW_VALUE >> 8) & (0b11111111); \
_CAN_BYTES_DATA_TO_WRITE.byte_4 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_4 |= ( _RAW_VALUE >> 16) & (0b11111111); \
_CAN_BYTES_DATA_TO_WRITE.byte_5 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_5 |= ( _RAW_VALUE >> 24) & (0b11111111); \
_CAN_BYTES_DATA_TO_WRITE.byte_6 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_6 |= ( _RAW_VALUE >> 32) & (0b11111111); \
_CAN_BYTES_DATA_TO_WRITE.byte_7 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_7 |= ( _RAW_VALUE >> 40) & (0b11111111); \



/************************************************************/
// Message: IHM_QSPY_VPU
/************************************************************/
#define MODULINK_CAN_MSG_IHM_QSPY_VPU MODULINK_CAN_MSG_IHM_QSPY_VPU
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_FRAME_ID 0xff8300

// Signal: IHM_BUFFER_DATA_SENDED_VPU
#define MODULINK_CAN_SIG_IHM_BUFFER_DATA_SENDED_VPU MODULINK_CAN_SIG_IHM_BUFFER_DATA_SENDED_VPU
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_CAN_SIG_IHM_BUFFER_DATA_SENDED_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_BUFFER_DATA_SENDED_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_BUFFER_DATA_SENDED_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_BUFFER_DATA_SENDED_VPU_MINIMUM 1
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_BUFFER_DATA_SENDED_VPU_MAXIMUM 7
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_BUFFER_DATA_SENDED_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_BUFFER_DATA_SENDED_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \


// Signal: IHM_QSPY_BYTE_0_VPU
#define MODULINK_CAN_SIG_IHM_QSPY_BYTE_0_VPU MODULINK_CAN_SIG_IHM_QSPY_BYTE_0_VPU
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_CAN_SIG_IHM_QSPY_BYTE_0_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_0_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_0_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_0_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_0_VPU_MAXIMUM 255
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_0_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_1) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_0_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \


// Signal: IHM_QSPY_BYTE_1_VPU
#define MODULINK_CAN_SIG_IHM_QSPY_BYTE_1_VPU MODULINK_CAN_SIG_IHM_QSPY_BYTE_1_VPU
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_CAN_SIG_IHM_QSPY_BYTE_1_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_1_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_1_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_1_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_1_VPU_MAXIMUM 255
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_1_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_2) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_1_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_2 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_2 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \


// Signal: IHM_QSPY_BYTE_2_VPU
#define MODULINK_CAN_SIG_IHM_QSPY_BYTE_2_VPU MODULINK_CAN_SIG_IHM_QSPY_BYTE_2_VPU
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_CAN_SIG_IHM_QSPY_BYTE_2_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_2_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_2_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_2_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_2_VPU_MAXIMUM 255
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_2_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_3) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_2_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_3 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_3 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \


// Signal: IHM_QSPY_BYTE_3_VPU
#define MODULINK_CAN_SIG_IHM_QSPY_BYTE_3_VPU MODULINK_CAN_SIG_IHM_QSPY_BYTE_3_VPU
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_CAN_SIG_IHM_QSPY_BYTE_3_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_3_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_3_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_3_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_3_VPU_MAXIMUM 255
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_3_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_4) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_3_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_4 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_4 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \


// Signal: IHM_QSPY_BYTE_4_VPU
#define MODULINK_CAN_SIG_IHM_QSPY_BYTE_4_VPU MODULINK_CAN_SIG_IHM_QSPY_BYTE_4_VPU
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_CAN_SIG_IHM_QSPY_BYTE_4_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_4_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_4_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_4_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_4_VPU_MAXIMUM 255
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_4_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_5) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_4_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_5 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_5 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \


// Signal: IHM_QSPY_BYTE_5_VPU
#define MODULINK_CAN_SIG_IHM_QSPY_BYTE_5_VPU MODULINK_CAN_SIG_IHM_QSPY_BYTE_5_VPU
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_CAN_SIG_IHM_QSPY_BYTE_5_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_5_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_5_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_5_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_5_VPU_MAXIMUM 255
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_5_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_6) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_5_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_6 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_6 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \


// Signal: IHM_QSPY_BYTE_6_VPU
#define MODULINK_CAN_SIG_IHM_QSPY_BYTE_6_VPU MODULINK_CAN_SIG_IHM_QSPY_BYTE_6_VPU
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_CAN_SIG_IHM_QSPY_BYTE_6_VPU_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_6_VPU_SCALE 1
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_6_VPU_OFFSET 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_6_VPU_MINIMUM 0
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_6_VPU_MAXIMUM 255
#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_6_VPU_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_7) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_IHM_QSPY_VPU_MODULINK_CAN_SIG_IHM_QSPY_BYTE_6_VPU_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_7 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_7 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \



/************************************************************/
// Message: VPU_MEASURES_1
/************************************************************/
#define MODULINK_CAN_MSG_VPU_MEASURES_1 MODULINK_CAN_MSG_VPU_MEASURES_1
#define MODULINK_CAN_MSG_VPU_MEASURES_1_FRAME_ID 0xffa001

// Signal: VPU_SKIIP_1_CURRENT
#define MODULINK_CAN_SIG_VPU_SKIIP_1_CURRENT MODULINK_CAN_SIG_VPU_SKIIP_1_CURRENT
#define MODULINK_CAN_MSG_VPU_MEASURES_1_CAN_SIG_VPU_SKIIP_1_CURRENT_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_1_CURRENT_SCALE 0.1
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_1_CURRENT_OFFSET -3000
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_1_CURRENT_MINIMUM -3000
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_1_CURRENT_MAXIMUM 3000
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_1_CURRENT_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 0 & 0b11111111 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_1) & 0b11111111) << 8 )

#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_1_CURRENT_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( _RAW_VALUE >> 8) & (0b11111111); \


// Signal: VPU_SKIIP_2_CURRENT
#define MODULINK_CAN_SIG_VPU_SKIIP_2_CURRENT MODULINK_CAN_SIG_VPU_SKIIP_2_CURRENT
#define MODULINK_CAN_MSG_VPU_MEASURES_1_CAN_SIG_VPU_SKIIP_2_CURRENT_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_2_CURRENT_SCALE 0.1
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_2_CURRENT_OFFSET -3000
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_2_CURRENT_MINIMUM -3000
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_2_CURRENT_MAXIMUM 3000
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_2_CURRENT_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_2) >> 0 & 0b11111111 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_3) & 0b11111111) << 8 )

#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_2_CURRENT_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_2 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_2 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \
_CAN_BYTES_DATA_TO_WRITE.byte_3 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_3 |= ( _RAW_VALUE >> 8) & (0b11111111); \


// Signal: VPU_SKIIP_1_VOLTAGE
#define MODULINK_CAN_SIG_VPU_SKIIP_1_VOLTAGE MODULINK_CAN_SIG_VPU_SKIIP_1_VOLTAGE
#define MODULINK_CAN_MSG_VPU_MEASURES_1_CAN_SIG_VPU_SKIIP_1_VOLTAGE_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_1_VOLTAGE_SCALE 0.1
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_1_VOLTAGE_OFFSET 0
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_1_VOLTAGE_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_1_VOLTAGE_MAXIMUM 2000
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_1_VOLTAGE_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_4) >> 0 & 0b11111111 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_5) & 0b11111111) << 8 )

#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_1_VOLTAGE_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_4 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_4 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \
_CAN_BYTES_DATA_TO_WRITE.byte_5 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_5 |= ( _RAW_VALUE >> 8) & (0b11111111); \


// Signal: VPU_SKIIP_2_VOLTAGE
#define MODULINK_CAN_SIG_VPU_SKIIP_2_VOLTAGE MODULINK_CAN_SIG_VPU_SKIIP_2_VOLTAGE
#define MODULINK_CAN_MSG_VPU_MEASURES_1_CAN_SIG_VPU_SKIIP_2_VOLTAGE_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_2_VOLTAGE_SCALE 0.1
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_2_VOLTAGE_OFFSET 0
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_2_VOLTAGE_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_2_VOLTAGE_MAXIMUM 2000
#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_2_VOLTAGE_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_6) >> 0 & 0b11111111 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_7) & 0b11111111) << 8 )

#define MODULINK_CAN_MSG_VPU_MEASURES_1_MODULINK_CAN_SIG_VPU_SKIIP_2_VOLTAGE_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_6 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_6 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \
_CAN_BYTES_DATA_TO_WRITE.byte_7 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_7 |= ( _RAW_VALUE >> 8) & (0b11111111); \



/************************************************************/
// Message: VPU_MEASURES_2
/************************************************************/
#define MODULINK_CAN_MSG_VPU_MEASURES_2 MODULINK_CAN_MSG_VPU_MEASURES_2
#define MODULINK_CAN_MSG_VPU_MEASURES_2_FRAME_ID 0xffa101

// Signal: VPU_VL
#define MODULINK_CAN_SIG_VPU_VL MODULINK_CAN_SIG_VPU_VL
#define MODULINK_CAN_MSG_VPU_MEASURES_2_CAN_SIG_VPU_VL_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_VL_SCALE 0.001
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_VL_OFFSET -10
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_VL_MINIMUM -10
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_VL_MAXIMUM 10
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_VL_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 0 & 0b11111111 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_1) & 0b11111111) << 8 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_2) & 0b11111111) << 16 )

#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_VL_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( _RAW_VALUE >> 8) & (0b11111111); \
_CAN_BYTES_DATA_TO_WRITE.byte_2 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_2 |= ( _RAW_VALUE >> 16) & (0b11111111); \


// Signal: VPU_D_VIN
#define MODULINK_CAN_SIG_VPU_D_VIN MODULINK_CAN_SIG_VPU_D_VIN
#define MODULINK_CAN_MSG_VPU_MEASURES_2_CAN_SIG_VPU_D_VIN_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_D_VIN_SCALE 0.001
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_D_VIN_OFFSET 0
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_D_VIN_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_D_VIN_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_D_VIN_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_3) >> 0 & 0b11111111 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_4) & 0b00000011) << 8 )

#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_D_VIN_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_3 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_3 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \
_CAN_BYTES_DATA_TO_WRITE.byte_4 &= 0b11111100; \
_CAN_BYTES_DATA_TO_WRITE.byte_4 |= ( _RAW_VALUE >> 8) & (0b00000011); \


// Signal: VPU_D_VOUT
#define MODULINK_CAN_SIG_VPU_D_VOUT MODULINK_CAN_SIG_VPU_D_VOUT
#define MODULINK_CAN_MSG_VPU_MEASURES_2_CAN_SIG_VPU_D_VOUT_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_D_VOUT_SCALE 0.001
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_D_VOUT_OFFSET 0
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_D_VOUT_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_D_VOUT_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_D_VOUT_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_4) >> 2 & 0b00111111 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_5) & 0b00001111) << 6 )

#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_D_VOUT_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_4 &= (0b00000011);\
_CAN_BYTES_DATA_TO_WRITE.byte_4 |= ( ( _RAW_VALUE & 0b00111111 ) << 2); \
_CAN_BYTES_DATA_TO_WRITE.byte_5 &= 0b11110000; \
_CAN_BYTES_DATA_TO_WRITE.byte_5 |= ( _RAW_VALUE >> 6) & (0b00001111); \


// Signal: VPU_P_COMP
#define MODULINK_CAN_SIG_VPU_P_COMP MODULINK_CAN_SIG_VPU_P_COMP
#define MODULINK_CAN_MSG_VPU_MEASURES_2_CAN_SIG_VPU_P_COMP_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_P_COMP_SCALE 0.1
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_P_COMP_OFFSET -50
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_P_COMP_MINIMUM -50
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_P_COMP_MAXIMUM 50
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_P_COMP_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_5) >> 4 & 0b00001111 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_6) & 0b00111111) << 4 )

#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_P_COMP_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_5 &= (0b00001111);\
_CAN_BYTES_DATA_TO_WRITE.byte_5 |= ( ( _RAW_VALUE & 0b00001111 ) << 4); \
_CAN_BYTES_DATA_TO_WRITE.byte_6 &= 0b11000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_6 |= ( _RAW_VALUE >> 4) & (0b00111111); \


// Signal: VPU_I_COMP
#define MODULINK_CAN_SIG_VPU_I_COMP MODULINK_CAN_SIG_VPU_I_COMP
#define MODULINK_CAN_MSG_VPU_MEASURES_2_CAN_SIG_VPU_I_COMP_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_I_COMP_SCALE 0.1
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_I_COMP_OFFSET -50
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_I_COMP_MINIMUM -50
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_I_COMP_MAXIMUM 50
#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_I_COMP_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_6) >> 6 & 0b00000011 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_7) & 0b11111111) << 2 )

#define MODULINK_CAN_MSG_VPU_MEASURES_2_MODULINK_CAN_SIG_VPU_I_COMP_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_6 &= (0b00111111);\
_CAN_BYTES_DATA_TO_WRITE.byte_6 |= ( ( _RAW_VALUE & 0b00000011 ) << 6); \
_CAN_BYTES_DATA_TO_WRITE.byte_7 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_7 |= ( _RAW_VALUE >> 2) & (0b11111111); \



/************************************************************/
// Message: VPU_SETPOINTS_1
/************************************************************/
#define MODULINK_CAN_MSG_VPU_SETPOINTS_1 MODULINK_CAN_MSG_VPU_SETPOINTS_1
#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_FRAME_ID 0xffa201

// Signal: VPU_IND_FSBB_CURRENT_SP
#define MODULINK_CAN_SIG_VPU_IND_FSBB_CURRENT_SP MODULINK_CAN_SIG_VPU_IND_FSBB_CURRENT_SP
#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_CAN_SIG_VPU_IND_FSBB_CURRENT_SP_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_MODULINK_CAN_SIG_VPU_IND_FSBB_CURRENT_SP_SCALE 1
#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_MODULINK_CAN_SIG_VPU_IND_FSBB_CURRENT_SP_OFFSET -2500
#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_MODULINK_CAN_SIG_VPU_IND_FSBB_CURRENT_SP_MINIMUM -2500
#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_MODULINK_CAN_SIG_VPU_IND_FSBB_CURRENT_SP_MAXIMUM 2500
#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_MODULINK_CAN_SIG_VPU_IND_FSBB_CURRENT_SP_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 0 & 0b11111111 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_1) & 0b11111111) << 8 )

#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_MODULINK_CAN_SIG_VPU_IND_FSBB_CURRENT_SP_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( _RAW_VALUE >> 8) & (0b11111111); \


// Signal: VPU_FSSB_POWER_SP
#define MODULINK_CAN_SIG_VPU_FSSB_POWER_SP MODULINK_CAN_SIG_VPU_FSSB_POWER_SP
#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_CAN_SIG_VPU_FSSB_POWER_SP_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_MODULINK_CAN_SIG_VPU_FSSB_POWER_SP_SCALE 1
#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_MODULINK_CAN_SIG_VPU_FSSB_POWER_SP_OFFSET 0
#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_MODULINK_CAN_SIG_VPU_FSSB_POWER_SP_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_MODULINK_CAN_SIG_VPU_FSSB_POWER_SP_MAXIMUM 2000
#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_MODULINK_CAN_SIG_VPU_FSSB_POWER_SP_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_2) >> 0 & 0b11111111 ) | \
 ( ( ( _CAN_BYTES_DATA.byte_3) & 0b11111111) << 8 )

#define MODULINK_CAN_MSG_VPU_SETPOINTS_1_MODULINK_CAN_SIG_VPU_FSSB_POWER_SP_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_2 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_2 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \
_CAN_BYTES_DATA_TO_WRITE.byte_3 &= 0b00000000; \
_CAN_BYTES_DATA_TO_WRITE.byte_3 |= ( _RAW_VALUE >> 8) & (0b11111111); \



/************************************************************/
// Message: VPU_FAULTS_1
/************************************************************/
#define MODULINK_CAN_MSG_VPU_FAULTS_1 MODULINK_CAN_MSG_VPU_FAULTS_1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_FRAME_ID 0xffa301

// Signal: VPU_SKIIP1_OVERVOLTAGE
#define MODULINK_CAN_SIG_VPU_SKIIP1_OVERVOLTAGE MODULINK_CAN_SIG_VPU_SKIIP1_OVERVOLTAGE
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_SKIIP1_OVERVOLTAGE_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERVOLTAGE_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERVOLTAGE_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERVOLTAGE_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERVOLTAGE_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERVOLTAGE_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 0 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERVOLTAGE_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b11111110);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b00000001 ) << 0); \


// Signal: VPU_SKIIP1_OVERCURRENT
#define MODULINK_CAN_SIG_VPU_SKIIP1_OVERCURRENT MODULINK_CAN_SIG_VPU_SKIIP1_OVERCURRENT
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_SKIIP1_OVERCURRENT_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERCURRENT_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERCURRENT_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERCURRENT_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERCURRENT_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERCURRENT_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 1 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERCURRENT_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b11111101);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b00000001 ) << 1); \


// Signal: VPU_SKIIP1_OVERHEAT
#define MODULINK_CAN_SIG_VPU_SKIIP1_OVERHEAT MODULINK_CAN_SIG_VPU_SKIIP1_OVERHEAT
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_SKIIP1_OVERHEAT_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERHEAT_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERHEAT_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERHEAT_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERHEAT_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERHEAT_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 2 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_OVERHEAT_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b11111011);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b00000001 ) << 2); \


// Signal: VPU_SKIIP1_HALT
#define MODULINK_CAN_SIG_VPU_SKIIP1_HALT MODULINK_CAN_SIG_VPU_SKIIP1_HALT
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_SKIIP1_HALT_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_HALT_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_HALT_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_HALT_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_HALT_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_HALT_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 3 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_HALT_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b11110111);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b00000001 ) << 3); \


// Signal: VPU_SKIIP1_ERROR
#define MODULINK_CAN_SIG_VPU_SKIIP1_ERROR MODULINK_CAN_SIG_VPU_SKIIP1_ERROR
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_SKIIP1_ERROR_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_ERROR_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_ERROR_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_ERROR_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_ERROR_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_ERROR_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 4 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_ERROR_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b11101111);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b00000001 ) << 4); \


// Signal: VPU_SKIIP2_OVERVOLTAGE
#define MODULINK_CAN_SIG_VPU_SKIIP2_OVERVOLTAGE MODULINK_CAN_SIG_VPU_SKIIP2_OVERVOLTAGE
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_SKIIP2_OVERVOLTAGE_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERVOLTAGE_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERVOLTAGE_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERVOLTAGE_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERVOLTAGE_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERVOLTAGE_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 5 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERVOLTAGE_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b11011111);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b00000001 ) << 5); \


// Signal: VPU_SKIIP2_OVERCURRENT
#define MODULINK_CAN_SIG_VPU_SKIIP2_OVERCURRENT MODULINK_CAN_SIG_VPU_SKIIP2_OVERCURRENT
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_SKIIP2_OVERCURRENT_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERCURRENT_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERCURRENT_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERCURRENT_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERCURRENT_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERCURRENT_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 6 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERCURRENT_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b10111111);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b00000001 ) << 6); \


// Signal: VPU_SKIIP2_OVERHEAT
#define MODULINK_CAN_SIG_VPU_SKIIP2_OVERHEAT MODULINK_CAN_SIG_VPU_SKIIP2_OVERHEAT
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_SKIIP2_OVERHEAT_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERHEAT_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERHEAT_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERHEAT_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERHEAT_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERHEAT_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 7 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_OVERHEAT_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b01111111);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b00000001 ) << 7); \


// Signal: VPU_SKIIP2_HALT
#define MODULINK_CAN_SIG_VPU_SKIIP2_HALT MODULINK_CAN_SIG_VPU_SKIIP2_HALT
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_SKIIP2_HALT_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_HALT_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_HALT_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_HALT_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_HALT_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_HALT_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_1) >> 0 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_HALT_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= (0b11111110);\
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( ( _RAW_VALUE & 0b00000001 ) << 0); \


// Signal: VPU_SKIIP2_ERROR
#define MODULINK_CAN_SIG_VPU_SKIIP2_ERROR MODULINK_CAN_SIG_VPU_SKIIP2_ERROR
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_SKIIP2_ERROR_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_ERROR_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_ERROR_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_ERROR_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_ERROR_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_ERROR_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_1) >> 1 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_ERROR_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= (0b11111101);\
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( ( _RAW_VALUE & 0b00000001 ) << 1); \


// Signal: VPU_INDUCTOR_OVERHEAT
#define MODULINK_CAN_SIG_VPU_INDUCTOR_OVERHEAT MODULINK_CAN_SIG_VPU_INDUCTOR_OVERHEAT
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_INDUCTOR_OVERHEAT_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_INDUCTOR_OVERHEAT_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_INDUCTOR_OVERHEAT_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_INDUCTOR_OVERHEAT_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_INDUCTOR_OVERHEAT_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_INDUCTOR_OVERHEAT_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_1) >> 2 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_INDUCTOR_OVERHEAT_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= (0b11111011);\
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( ( _RAW_VALUE & 0b00000001 ) << 2); \


// Signal: VPU_CAPACITOR_OVERHEAT
#define MODULINK_CAN_SIG_VPU_CAPACITOR_OVERHEAT MODULINK_CAN_SIG_VPU_CAPACITOR_OVERHEAT
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_CAPACITOR_OVERHEAT_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CAPACITOR_OVERHEAT_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CAPACITOR_OVERHEAT_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CAPACITOR_OVERHEAT_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CAPACITOR_OVERHEAT_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CAPACITOR_OVERHEAT_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_1) >> 3 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CAPACITOR_OVERHEAT_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= (0b11110111);\
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( ( _RAW_VALUE & 0b00000001 ) << 3); \


// Signal: VPU_SETTLE_TIMEOUT
#define MODULINK_CAN_SIG_VPU_SETTLE_TIMEOUT MODULINK_CAN_SIG_VPU_SETTLE_TIMEOUT
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_SETTLE_TIMEOUT_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SETTLE_TIMEOUT_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SETTLE_TIMEOUT_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SETTLE_TIMEOUT_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SETTLE_TIMEOUT_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SETTLE_TIMEOUT_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_1) >> 4 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SETTLE_TIMEOUT_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= (0b11101111);\
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( ( _RAW_VALUE & 0b00000001 ) << 4); \


// Signal: VPU_CLA_T1_WATCHDOG_TIMEOUT
#define MODULINK_CAN_SIG_VPU_CLA_T1_WATCHDOG_TIMEOUT MODULINK_CAN_SIG_VPU_CLA_T1_WATCHDOG_TIMEOUT
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_CLA_T1_WATCHDOG_TIMEOUT_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CLA_T1_WATCHDOG_TIMEOUT_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CLA_T1_WATCHDOG_TIMEOUT_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CLA_T1_WATCHDOG_TIMEOUT_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CLA_T1_WATCHDOG_TIMEOUT_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CLA_T1_WATCHDOG_TIMEOUT_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_1) >> 5 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CLA_T1_WATCHDOG_TIMEOUT_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= (0b11011111);\
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( ( _RAW_VALUE & 0b00000001 ) << 5); \


// Signal: VPU_CLA_T2_WATCHDOG_TIMEOUT
#define MODULINK_CAN_SIG_VPU_CLA_T2_WATCHDOG_TIMEOUT MODULINK_CAN_SIG_VPU_CLA_T2_WATCHDOG_TIMEOUT
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_CLA_T2_WATCHDOG_TIMEOUT_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CLA_T2_WATCHDOG_TIMEOUT_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CLA_T2_WATCHDOG_TIMEOUT_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CLA_T2_WATCHDOG_TIMEOUT_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CLA_T2_WATCHDOG_TIMEOUT_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CLA_T2_WATCHDOG_TIMEOUT_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_1) >> 6 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_CLA_T2_WATCHDOG_TIMEOUT_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= (0b10111111);\
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( ( _RAW_VALUE & 0b00000001 ) << 6); \


// Signal: VPU_EMERGENCY_SHUTDOWN
#define MODULINK_CAN_SIG_VPU_EMERGENCY_SHUTDOWN MODULINK_CAN_SIG_VPU_EMERGENCY_SHUTDOWN
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_EMERGENCY_SHUTDOWN_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_EMERGENCY_SHUTDOWN_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_EMERGENCY_SHUTDOWN_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_EMERGENCY_SHUTDOWN_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_EMERGENCY_SHUTDOWN_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_EMERGENCY_SHUTDOWN_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_1) >> 7 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_EMERGENCY_SHUTDOWN_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= (0b01111111);\
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( ( _RAW_VALUE & 0b00000001 ) << 7); \


// Signal: VPU_SKIIP1_CARDIAC_ARRREST
#define MODULINK_CAN_SIG_VPU_SKIIP1_CARDIAC_ARRREST MODULINK_CAN_SIG_VPU_SKIIP1_CARDIAC_ARRREST
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_SKIIP1_CARDIAC_ARRREST_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_CARDIAC_ARRREST_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_CARDIAC_ARRREST_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_CARDIAC_ARRREST_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_CARDIAC_ARRREST_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_CARDIAC_ARRREST_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_2) >> 0 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP1_CARDIAC_ARRREST_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_2 &= (0b11111110);\
_CAN_BYTES_DATA_TO_WRITE.byte_2 |= ( ( _RAW_VALUE & 0b00000001 ) << 0); \


// Signal: VPU_SKIIP2_CARDIAC_ARRREST
#define MODULINK_CAN_SIG_VPU_SKIIP2_CARDIAC_ARRREST MODULINK_CAN_SIG_VPU_SKIIP2_CARDIAC_ARRREST
#define MODULINK_CAN_MSG_VPU_FAULTS_1_CAN_SIG_VPU_SKIIP2_CARDIAC_ARRREST_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_CARDIAC_ARRREST_SCALE 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_CARDIAC_ARRREST_OFFSET 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_CARDIAC_ARRREST_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_CARDIAC_ARRREST_MAXIMUM 1
#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_CARDIAC_ARRREST_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_2) >> 1 & 0b00000001 )

#define MODULINK_CAN_MSG_VPU_FAULTS_1_MODULINK_CAN_SIG_VPU_SKIIP2_CARDIAC_ARRREST_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_2 &= (0b11111101);\
_CAN_BYTES_DATA_TO_WRITE.byte_2 |= ( ( _RAW_VALUE & 0b00000001 ) << 1); \



/************************************************************/
// Message: VPU_QSPY
/************************************************************/
#define MODULINK_CAN_MSG_VPU_QSPY MODULINK_CAN_MSG_VPU_QSPY
#define MODULINK_CAN_MSG_VPU_QSPY_FRAME_ID 0xffa401

// Signal: VPU_BUFFER_DATA_SENDED
#define MODULINK_CAN_SIG_VPU_BUFFER_DATA_SENDED MODULINK_CAN_SIG_VPU_BUFFER_DATA_SENDED
#define MODULINK_CAN_MSG_VPU_QSPY_CAN_SIG_VPU_BUFFER_DATA_SENDED_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_BUFFER_DATA_SENDED_SCALE 1
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_BUFFER_DATA_SENDED_OFFSET 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_BUFFER_DATA_SENDED_MINIMUM 1
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_BUFFER_DATA_SENDED_MAXIMUM 7
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_BUFFER_DATA_SENDED_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_0) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_BUFFER_DATA_SENDED_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_0 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_0 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \


// Signal: VPU_QSPY_BYTE_0
#define MODULINK_CAN_SIG_VPU_QSPY_BYTE_0 MODULINK_CAN_SIG_VPU_QSPY_BYTE_0
#define MODULINK_CAN_MSG_VPU_QSPY_CAN_SIG_VPU_QSPY_BYTE_0_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_0_SCALE 1
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_0_OFFSET 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_0_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_0_MAXIMUM 255
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_0_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_1) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_0_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_1 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_1 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \


// Signal: VPU_QSPY_BYTE_1
#define MODULINK_CAN_SIG_VPU_QSPY_BYTE_1 MODULINK_CAN_SIG_VPU_QSPY_BYTE_1
#define MODULINK_CAN_MSG_VPU_QSPY_CAN_SIG_VPU_QSPY_BYTE_1_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_1_SCALE 1
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_1_OFFSET 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_1_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_1_MAXIMUM 255
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_1_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_2) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_1_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_2 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_2 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \


// Signal: VPU_QSPY_BYTE_2
#define MODULINK_CAN_SIG_VPU_QSPY_BYTE_2 MODULINK_CAN_SIG_VPU_QSPY_BYTE_2
#define MODULINK_CAN_MSG_VPU_QSPY_CAN_SIG_VPU_QSPY_BYTE_2_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_2_SCALE 1
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_2_OFFSET 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_2_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_2_MAXIMUM 255
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_2_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_3) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_2_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_3 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_3 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \


// Signal: VPU_QSPY_BYTE_3
#define MODULINK_CAN_SIG_VPU_QSPY_BYTE_3 MODULINK_CAN_SIG_VPU_QSPY_BYTE_3
#define MODULINK_CAN_MSG_VPU_QSPY_CAN_SIG_VPU_QSPY_BYTE_3_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_3_SCALE 1
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_3_OFFSET 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_3_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_3_MAXIMUM 255
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_3_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_4) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_3_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_4 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_4 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \


// Signal: VPU_QSPY_BYTE_4
#define MODULINK_CAN_SIG_VPU_QSPY_BYTE_4 MODULINK_CAN_SIG_VPU_QSPY_BYTE_4
#define MODULINK_CAN_MSG_VPU_QSPY_CAN_SIG_VPU_QSPY_BYTE_4_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_4_SCALE 1
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_4_OFFSET 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_4_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_4_MAXIMUM 255
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_4_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_5) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_4_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_5 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_5 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \


// Signal: VPU_QSPY_BYTE_5
#define MODULINK_CAN_SIG_VPU_QSPY_BYTE_5 MODULINK_CAN_SIG_VPU_QSPY_BYTE_5
#define MODULINK_CAN_MSG_VPU_QSPY_CAN_SIG_VPU_QSPY_BYTE_5_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_5_SCALE 1
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_5_OFFSET 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_5_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_5_MAXIMUM 255
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_5_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_6) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_5_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_6 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_6 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \


// Signal: VPU_QSPY_BYTE_6
#define MODULINK_CAN_SIG_VPU_QSPY_BYTE_6 MODULINK_CAN_SIG_VPU_QSPY_BYTE_6
#define MODULINK_CAN_MSG_VPU_QSPY_CAN_SIG_VPU_QSPY_BYTE_6_TRANSMISSION_TYPE uint64_t
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_6_SCALE 1
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_6_OFFSET 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_6_MINIMUM 0
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_6_MAXIMUM 255
#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_6_GET_RAW_DATA(_CAN_BYTES_DATA) \
( ( _CAN_BYTES_DATA.byte_7) >> 0 & 0b11111111 )

#define MODULINK_CAN_MSG_VPU_QSPY_MODULINK_CAN_SIG_VPU_QSPY_BYTE_6_WRITE_RAW_DATA( _CAN_BYTES_DATA_TO_WRITE , _RAW_VALUE ) \
_CAN_BYTES_DATA_TO_WRITE.byte_7 &= (0b00000000);\
_CAN_BYTES_DATA_TO_WRITE.byte_7 |= ( ( _RAW_VALUE & 0b11111111 ) << 0); \



/************************************************************/
// Message: VPU_SYSTEM_STATUS
/************************************************************/
#define MODULINK_CAN_MSG_VPU_SYSTEM_STATUS MODULINK_CAN_MSG_VPU_SYSTEM_STATUS
#define MODULINK_CAN_MSG_VPU_SYSTEM_STATUS_FRAME_ID 0xffa501



//arg _CAN_MSG: the name of the message with prefix CAN_MSG_ 
//arg _CAN_SIG: the name of the signal  with prefix CAN_SIG_ 
//arg _ENCODED_VALUE: encoded value 
//return VALUE: value decoded 

#define CAN_SIG_DECODE( _CAN_MSG , _CAN_SIG , _ENCODED_VALUE ) \
( ( (uint64_t) _ENCODED_VALUE ) * ( (float32_t) _CAN_MSG##_##_CAN_SIG##_SCALE) + _CAN_MSG##_##_CAN_SIG##_OFFSET )


//arg _CAN_MSG: the name of the message with prefix CAN_MSG_ 
//arg _CAN_SIG: the name of the signal  with prefix CAN_SIG_ 
//arg _VALUE: the value to be encoded 
//return SIG_PAYLOAD: the value encoded 

#define CAN_SIG_ENCODE( _CAN_MSG , _CAN_SIG , _VALUE ) \
( uint64_t ) ( ( _VALUE - _CAN_MSG##_##_CAN_SIG##_OFFSET)/( (float) _CAN_MSG##_##_CAN_SIG##_SCALE ) )


//arg _CAN_MSG: the name of the message with prefix CAN_MSG_ 
//arg _CAN_SIG: the name of the signal  with prefix CAN_SIG_ 
//arg _VALUE: the value to be encoded 
//return IS_VALID: boolean informing if this value is valid

#define CAN_SIG_IS_VALID( _CAN_MSG , _CAN_SIG , _VALUE ) \
( _CAN_MSG##_##_CAN_SIG##_MINIMUM <= _VALUE ) && ( _VALUE <= _CAN_MSG##_##_CAN_SIG##_MAXIMUM)


//arg _CAN_MSG: the name of the message with prefix CAN_MSG_ 
//arg _CAN_SIG: the name of the signal  with prefix CAN_SIG_ 
//arg _CAN_VALUE: the name of the value with prefix CAN_VALUE 
//return VALUE: value of the named value

#define CAN_GET_VALUE_BY_NAME( _CAN_MSG , _CAN_SIG , _CAN_VALUE ) \
( _CAN_MSG##_##_CAN_SIG##_##_CAN_VALUE )


//arg _CAN_MSG: the name of the message with prefix CAN_MSG_ 
//arg _CAN_SIG: the name of the signal  with prefix CAN_SIG_ 
//arg _CAN_BYTES_DATA: Can_Bytes_Data_t with the message payload 
//return ENCODED_VALUE: value of the signal before decode

#define CAN_GET_ENCODED_VALUE( _CAN_MSG , _CAN_SIG , _CAN_BYTES_DATA ) \
( _CAN_MSG##_##_CAN_SIG##_GET_RAW_DATA( _CAN_BYTES_DATA ) )



//arg _CAN_MSG: the name of the message with prefix CAN_MSG_ 
//arg _CAN_SIG: the name of the signal  with prefix CAN_SIG_ 
//arg _CAN_BYTES_DATA: Can_Bytes_Data_t with the message payload 
//return DECODED_VALUE: value of the signal decoded

#define CAN_GET_DECODED_VALUE( _CAN_MSG , _CAN_SIG , _CAN_BYTES_DATA ) \
 CAN_SIG_DECODE(  _CAN_MSG , _CAN_SIG , CAN_GET_ENCODED_VALUE( _CAN_MSG , _CAN_SIG , _CAN_BYTES_DATA ) ) 



//arg _CAN_MSG: the name of the message with prefix CAN_MSG_ 
//arg _CAN_SIG: the name of the signal  with prefix CAN_SIG_ 
//arg _CAN_BYTES_DATA: Can_Bytes_Data_t with the message payload 
//arg _ENCODED_VALUE: encoded Value to Set On Payload 
//return NONE
#define CAN_WRITE_ENCODED_VALUE( _CAN_MSG , _CAN_SIG , _CAN_BYTES_DATA , _ENCODED_VALUE ) \
_CAN_MSG##_##_CAN_SIG##_WRITE_RAW_DATA( _CAN_BYTES_DATA , _ENCODED_VALUE ) 



//arg _CAN_MSG: the name of the message with prefix CAN_MSG_ 
//arg _CAN_SIG: the name of the signal  with prefix CAN_SIG_ 
//arg _CAN_BYTES_DATA: Can_Bytes_Data_t with the message payload 
//arg _DECODED_VALUE: decoded Value to Set On Payload 
//return NONE
#define CAN_WRITE_DECODED_VALUE( _CAN_MSG , _CAN_SIG , _CAN_BYTES_DATA , _DECODED_VALUE ) \
CAN_WRITE_ENCODED_VALUE( _CAN_MSG , _CAN_SIG , _CAN_BYTES_DATA , CAN_SIG_ENCODE( _CAN_MSG , _CAN_SIG , _DECODED_VALUE ) ) 



//arg _CAN_MSG: the name of the message with prefix CAN_MSG_ 
//arg _CAN_SIG: the name of the signal  with prefix CAN_SIG_ 
//arg _CAN_BYTES_DATA: Can_Bytes_Data_t with the message payload 
//arg _NAMED_VALUE: Named Value to Set On Payload 
//return NONE
#define CAN_WRITE_NAMED_VALUE( _CAN_MSG , _CAN_SIG , _CAN_BYTES_DATA , _NAMED_VALUE ) \
CAN_WRITE_ENCODED_VALUE( _CAN_MSG , _CAN_SIG , _CAN_BYTES_DATA ,  CAN_GET_VALUE_BY_NAME( _CAN_MSG , _CAN_SIG , _NAMED_VALUE) ) 

enum{
    MODULINK_CAN_MSG_NONE_INDEX=0U,
    MODULINK_CAN_MSG_EXT_IN_INDEX,
    MODULINK_CAN_MSG_VPU_MEASURES_1_INDEX,
    MODULINK_CAN_MSG_VPU_MEASURES_2_INDEX,
    MODULINK_CAN_MSG_VPU_SETPOINTS_1_INDEX,
    MODULINK_CAN_MSG_VPU_FAULTS_1_INDEX,
    MODULINK_CAN_MSG_VPU_QSPY_INDEX,
    MODULINK_CAN_MSG_VPU_SYSTEM_STATUS_INDEX,
    MODULINK_CAN_MAX_MSG,
};

typedef struct{
    uint32_t         msg_id;
    CAN_MsgFrameType frame_type;
    CAN_MsgObjType   msg_type;
    uint32_t         mask;
    uint32_t         flags;
    uint16_t         dlc;
}MessageProprieties_t;

extern const MessageProprieties_t modulink_can_messages_proprieties[MODULINK_CAN_MAX_MSG];

#endif
