//$file${.::Cores_Project::CPU1::qm_files::OCs::oc_spi::oc_spi.c} vvvvvvvvvvvv
//
// Model: main_model.qm
// File:  ${.::Cores_Project::CPU1::qm_files::OCs::oc_spi::oc_spi.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Cores_Project::CPU1::qm_files::OCs::oc_spi::oc_spi.c} ^^^^^^^^^
#include "./oc_spi.h"

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${OCs::OC_SPI} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${OCs::OC_SPI::OC_SPI} .....................................................

//${OCs::OC_SPI::OC_SPI::ctor} ...............................................
void OC_SPI_ctor(OC_SPI * const me,
    QActive * const owner,
    uint16_t id)
{
    QHsm_ctor(&me->super, Q_STATE_CAST(&OC_SPI_initial));
    me->owner = owner;
    me->id = id;
}

//${OCs::OC_SPI::OC_SPI::SM} .................................................
QState OC_SPI_initial(OC_SPI * const me, void const * const par) {
    //${OCs::OC_SPI::OC_SPI::SM::initial}
    return Q_TRAN(&OC_SPI_Waiting_QF);
}

//${OCs::OC_SPI::OC_SPI::SM::Waiting_QF} .....................................
QState OC_SPI_Waiting_QF(OC_SPI * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${OCs::OC_SPI::OC_SPI::SM::Waiting_QF}
        case Q_ENTRY_SIG: {
            //BSP_BKPT;
            status_ = Q_HANDLED();
            break;
        }
        //${OCs::OC_SPI::OC_SPI::SM::Waiting_QF::RUNNING_QF}
        case RUNNING_QF_SIG: {
            status_ = Q_TRAN(&OC_SPI_Start);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${OCs::OC_SPI::OC_SPI::SM::Start} ..........................................
QState OC_SPI_Start(OC_SPI * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${OCs::OC_SPI::OC_SPI::SM::Start}
        case Q_ENTRY_SIG: {
            //BSP_BKPT;
            OC_SPI_local_queue_start(me);
            status_ = Q_HANDLED();
            break;
        }
        //${OCs::OC_SPI::OC_SPI::SM::Start::INIT_COMPLETE}
        case INIT_COMPLETE_SIG: {
            // MAX Config
            status_ = Q_TRAN(&OC_SPI_Operation);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${OCs::OC_SPI::OC_SPI::SM::Operation} ......................................
QState OC_SPI_Operation(OC_SPI * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${OCs::OC_SPI::OC_SPI::SM::Operation}
        case Q_ENTRY_SIG: {
            //BSP_BKPT;
            status_ = Q_HANDLED();
            break;
        }
        //${OCs::OC_SPI::OC_SPI::SM::Operation::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&OC_SPI_Waiting_Request);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${OCs::OC_SPI::OC_SPI::SM::Operation::Waiting_Request} .....................
QState OC_SPI_Waiting_Request(OC_SPI * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${OCs::OC_SPI::OC_SPI::SM::Operation::Waiting_Request::SPI_SEND_MSG}
        case SPI_SEND_MSG_SIG: {
            OC_Evt_SPI_Message_t const * message = Q_EVT_CAST(OC_Evt_SPI_Message_t);
            OC_SPI_spi_send_message(me, message->message);
            status_ = Q_TRAN(&OC_SPI_Waiting_Response);
            break;
        }
        default: {
            status_ = Q_SUPER(&OC_SPI_Operation);
            break;
        }
    }
    return status_;
}

//${OCs::OC_SPI::OC_SPI::SM::Operation::Waiting_Response} ....................
QState OC_SPI_Waiting_Response(OC_SPI * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${OCs::OC_SPI::OC_SPI::SM::Operation::Waiting_Response::SPI_MSG_RECEIVED}
        case SPI_MSG_RECEIVED_SIG: {
            OC_SPI_spi_receive_message(me);
            //${OCs::OC_SPI::OC_SPI::SM::Operation::Waiting_Response::SPI_MSG_RECEIVED::[OC_SPI_local_queue_receive(me,&~}
            if (OC_SPI_local_queue_receive( me , &me->last_message_sended )) {
                OC_SPI_spi_send_message(me, me->last_message_sended);
                status_ = Q_TRAN(&OC_SPI_Waiting_Response);
            }
            //${OCs::OC_SPI::OC_SPI::SM::Operation::Waiting_Response::SPI_MSG_RECEIVED::[else]}
            else {
                status_ = Q_TRAN(&OC_SPI_Waiting_Request);
            }
            break;
        }
        //${OCs::OC_SPI::OC_SPI::SM::Operation::Waiting_Response::SPI_SEND_MSG}
        case SPI_SEND_MSG_SIG: {

            OC_Evt_SPI_Message_t const * message = Q_EVT_CAST(OC_Evt_SPI_Message_t);
            OC_SPI_local_queue_send(me, &(message->message) );
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&OC_SPI_Operation);
            break;
        }
    }
    return status_;
}
//$enddef${OCs::OC_SPI} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
