//$file${.::Cores_Project::CPU1::qm_files::OCs::oc_spi::oc_spi.h} vvvvvvvvvvvv
//
// Model: main_model.qm
// File:  ${.::Cores_Project::CPU1::qm_files::OCs::oc_spi::oc_spi.h}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Cores_Project::CPU1::qm_files::OCs::oc_spi::oc_spi.h} ^^^^^^^^^
#ifndef OC_SPI_RTD_H_
#define OC_SPI_RTD_H_

#include "main_qm.h"

//$declare${OCs::OC_SPI} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${OCs::OC_SPI::OC_SPI} .....................................................
typedef struct {
// protected:
    QHsm super;

// private:
    QActive * owner;
    uint16_t id;
    QueueHandle_t queue_handler;
    SPI_Message_t queue_storage[10];
    StaticQueue_t queue_buffer;
    SPI_Message_t last_message_sended;

// public:
    SPI_Message_t message_request;
    uint16_t message_response;
} OC_SPI;

// public:
void OC_SPI_ctor(OC_SPI * const me,
    QActive * const owner,
    uint16_t id);

// private:
uint16_t OC_SPI_local_queue_start(OC_SPI * const me);
uint16_t OC_SPI_local_queue_send(OC_SPI * const me,
    SPI_Message_t const *  data);
uint16_t OC_SPI_local_queue_receive(OC_SPI * const me,
    SPI_Message_t * const data);
void OC_SPI_spi_send_message(OC_SPI * const me,
    SPI_Message_t message);
void OC_SPI_spi_receive_message(OC_SPI * const me);

// protected:
QState OC_SPI_initial(OC_SPI * const me, void const * const par);
QState OC_SPI_Waiting_QF(OC_SPI * const me, QEvt const * const e);
QState OC_SPI_Start(OC_SPI * const me, QEvt const * const e);
QState OC_SPI_Operation(OC_SPI * const me, QEvt const * const e);
QState OC_SPI_Waiting_Request(OC_SPI * const me, QEvt const * const e);
QState OC_SPI_Waiting_Response(OC_SPI * const me, QEvt const * const e);
//$enddecl${OCs::OC_SPI} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
