/*
 * communication_app.h
 *
 *  Created on: 23 de abr de 2024
 *      Author: ramon.martins
 */

#ifndef APPLICATION_ACTIVE_OBJECTS_COMMUNICATION_APP_COMMUNICATION_APP_H_
#define APPLICATION_ACTIVE_OBJECTS_COMMUNICATION_APP_COMMUNICATION_APP_H_





#endif /* APPLICATION_ACTIVE_OBJECTS_COMMUNICATION_APP_COMMUNICATION_APP_H_ */
