//$file${.::Cores_Project::CPU1::qm_files::AOs::ao_fsbb_control::fsbb_control.c} 
//
// Model: main_model.qm
// File:  ${.::Cores_Project::CPU1::qm_files::AOs::ao_fsbb_control::fsbb_control.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Cores_Project::CPU1::qm_files::AOs::ao_fsbb_control::fsbb_control.c} 
#include "./fsbb_control.h"

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${CPU1::AOs::AO_FSBB_Control} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CPU1::AOs::AO_FSBB_Control::FSBB_Control} ................................

//${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM} ............................
QState FSBB_Control_initial(FSBB_Control * const me, void const * const par) {
    //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::initial}
    return Q_TRAN(&FSBB_Control_Waiting_QF);
}

//${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Waiting_QF} ................
QState FSBB_Control_Waiting_QF(FSBB_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Waiting_QF}
        case Q_ENTRY_SIG: {
            QACTIVE_POST(&me->super,&im_evt_running_qf,(void *)0);
            status_ = Q_HANDLED();
            break;
        }
        //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Waiting_QF::RUNNING_QF}
        case RUNNING_QF_SIG: {
            status_ = Q_TRAN(&FSBB_Control_Start);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Start} .....................
QState FSBB_Control_Start(FSBB_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Start}
        case Q_ENTRY_SIG: {
            //BSP_BKPT;

            QACTIVE_POST(&me->super,&im_evt_init_complete,(void *)0);
            status_ = Q_HANDLED();
            break;
        }
        //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Start::INIT_COMPLETE}
        case INIT_COMPLETE_SIG: {
            status_ = Q_TRAN(&FSBB_Control_Uncharged);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation} .................
QState FSBB_Control_Operation(FSBB_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::RESET}
        case RESET_SIG: {
            status_ = Q_TRAN(&FSBB_Control_Uncharged);
            break;
        }
        //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::SET_FAULT, EMERGENCY_SHUTDOWN}
        case SET_FAULT_SIG: // intentionally fall through
        case EMERGENCY_SHUTDOWN_SIG: {
            status_ = Q_TRAN(&FSBB_Control_Fault);
            break;
        }
        //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::CHANGE_SETPOINT}
        case CHANGE_SETPOINT_SIG: {
            BSP_BKPT;

            AO_Evt_Change_Setpoint_t const * Evt_Change_Setpoint =  Q_EVT_CAST(AO_Evt_Change_Setpoint_t);

            if(Evt_Change_Setpoint->data.setpoint_id<NUM_OF_SETPOINTS){
                me->setpoints[Evt_Change_Setpoint->data.setpoint_id] = Evt_Change_Setpoint->data.setpoint_value*((float)0.01);
            }
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::Uncharged} ......
QState FSBB_Control_Uncharged(FSBB_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::Uncharged}
        case Q_ENTRY_SIG: {
            BSP_BKPT;
            status_ = Q_HANDLED();
            break;
        }
        //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::Uncharged::PRECHARGE_START}
        case PRECHARGE_START_SIG: {
            FSBB_Control_Start_Precharge(me,e);
            //BSP_BKPT;
            status_ = Q_TRAN(&FSBB_Control_Precharge);
            break;
        }
        default: {
            status_ = Q_SUPER(&FSBB_Control_Operation);
            break;
        }
    }
    return status_;
}

//${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::Precharge} ......
QState FSBB_Control_Precharge(FSBB_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::Precharge::PRECHARGE_FINISH}
        case PRECHARGE_FINISH_SIG: {
            FSBB_Control_Finish_Precharge(me,e);
            status_ = Q_TRAN(&FSBB_Control_Idle);
            break;
        }
        default: {
            status_ = Q_SUPER(&FSBB_Control_Operation);
            break;
        }
    }
    return status_;
}

//${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::Idle} ...........
QState FSBB_Control_Idle(FSBB_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::Idle::START_CONTROL}
        case START_CONTROL_SIG: {
            status_ = Q_TRAN(&FSBB_Control_Running);
            break;
        }
        default: {
            status_ = Q_SUPER(&FSBB_Control_Operation);
            break;
        }
    }
    return status_;
}

//${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::Running} ........
QState FSBB_Control_Running(FSBB_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::Running::STOP_CONTROL}
        case STOP_CONTROL_SIG: {
            status_ = Q_TRAN(&FSBB_Control_To_Idle);
            break;
        }
        default: {
            status_ = Q_SUPER(&FSBB_Control_Operation);
            break;
        }
    }
    return status_;
}

//${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::Fault} ..........
QState FSBB_Control_Fault(FSBB_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::Fault::CLEAR_FAULT}
        case CLEAR_FAULT_SIG: {
            status_ = Q_TRAN(&FSBB_Control_Uncharged);
            break;
        }
        default: {
            status_ = Q_SUPER(&FSBB_Control_Operation);
            break;
        }
    }
    return status_;
}

//${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::To_Idle} ........
QState FSBB_Control_To_Idle(FSBB_Control * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::To_Idle::UPDATE_PARAMS}
        case UPDATE_PARAMS_SIG: {
            //${CPU1::AOs::AO_FSBB_Control::FSBB_Control::SM::Operation::To_Idle::UPDATE_PARAMS::[10<IL_MIN_OPEN]}
            if (10 < IL_MIN_OPEN) {
                status_ = Q_TRAN(&FSBB_Control_Idle);
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&FSBB_Control_Operation);
            break;
        }
    }
    return status_;
}

//${CPU1::AOs::AO_FSBB_Control::inst_ao_fsbb_control} ........................
FSBB_Control inst_ao_fsbb_control;

//${CPU1::AOs::AO_FSBB_Control::globals::p_ao_fsbb_control} ..................
QActive * const p_ao_fsbb_control = &inst_ao_fsbb_control.super;

//${CPU1::AOs::AO_FSBB_Control::globals::ao_fsbb_control_ctor} ...............
void ao_fsbb_control_ctor(const QActive  * const pAO) {
    FSBB_Control * const me = (FSBB_Control *) pAO;
    QActive_ctor(&me->super, Q_STATE_CAST(&FSBB_Control_initial));
    QTimeEvt_ctorX(&me->time_evt_update_params, &me->super, UPDATE_PARAMS_SIG, 0U);
}
//$enddef${CPU1::AOs::AO_FSBB_Control} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
