//$file${.::Cores_Project::CM::qm_files::main_qm.h} vvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: main_model.qm
// File:  ${.::Cores_Project::CM::qm_files::main_qm.h}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Cores_Project::CM::qm_files::main_qm.h} ^^^^^^^^^^^^^^^^^^^^^^^
#ifndef MAIN_QM_H_
#define MAIN_QM_H_

#include "qpc.h"
#include "macros_qm.h"
#include "bsp_basic.h"

//================================================
//====================Signals=====================
//================================================

//$declare${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::Signals::com_signals_can} ........................................
enum com_signals_can {
    COM_SIG_CAN_MAX,
};

//${Shared::Signals::Communication IP~::com_signals_cpu1_cpu2_ipc} ...........
enum com_signals_cpu1_cpu2_ipc {
    //Index Signals Here
    COM_SIG_IPC_CPU1_CPU2_MAX,
};

//${Shared::Signals::Communication IP~::com_signals_cpu2_cpu1_ipc} ...........
enum com_signals_cpu2_cpu1_ipc {
    //Index Signals Here
    COM_SIG_IPC_CPU2_CPU1_MAX,
};

//${Shared::Signals::Communication IP~::com_signals_cpu1_cm_ipc} .............
enum com_signals_cpu1_cm_ipc {
    //Index Signals Here
    COM_SIG_IPC_CPU1_CM_MAX,
};

//${Shared::Signals::Communication IP~::com_signals_cm_cpu1_ipc} .............
enum com_signals_cm_cpu1_ipc {
    //Index Signals Here
    COM_SIG_IPC_CM_CPU1_MAX,
};

//${Shared::Signals::Communication IP~::com_signals_cpu2_cm_ipc} .............
enum com_signals_cpu2_cm_ipc {
    //Index Signals Here
    COM_SIG_IPC_CPU2_CM_MAX,
};

//${Shared::Signals::Communication IP~::com_signals_cm_cpu2_ipc} .............
enum com_signals_cm_cpu2_ipc {
    //Index Signals Here
    COM_SIG_IPC_CM_CPU2_MAX,
};

//${Shared::Types::Communication_Message_t} ..................................
typedef struct {
// private:
    uint16_t com_sig;
    uint16_t payload[MAX_SIG_PAYLOAD];
} Communication_Message_t;

//${Shared::Event_Types::OC_Evt} .............................................
typedef struct {
// protected:
    QEvt super;

// public:
    uint16_t ID;
} OC_Evt;

//${Shared::Event_Types::OC_TimeEvt} .........................................
typedef struct {
// protected:
    QTimeEvt super;

// public:
    uint16_t ID;
} OC_TimeEvt;

//${Shared::Event_Types::OC_Evt_Communication_Message_t} .....................
typedef struct {
// protected:
    OC_Evt super;

// public:
    Communication_Message_t msg;
} OC_Evt_Communication_Message_t;

//${Shared::Macros::OC_IPC_CMD_REMOTE_RESET} .................................
#define OC_IPC_CMD_REMOTE_RESET 0


//${Shared::Macros::OC_IPC_CMD_RESET_COMPLETE} ...............................
#define OC_IPC_CMD_RESET_COMPLETE 1

//${Shared::Macros::MAX_SIG_PAYLOAD} .........................................
#define MAX_SIG_PAYLOAD 5
//$enddecl${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${OCs::Signals} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${OCs::Signals::OC_IPC_SIGNALS} ............................................
#define OC_IPC_SIGNALS \
    IPC_RECEIVE_MSG_SIG,\
    IPC_SEND_MSG_SIG,\
    IPC_FULL_BUS_SIG,\
    IPC_RESET_CH_SIG,\
    IPC_REMOTE_RESET_SIG,\
    IPC_RESET_COMPLETE_SIG

//${OCs::Signals::OC_CAN_SIGNALS} ............................................
#define OC_CAN_SIGNALS \
    CAN_RECEIVE_MSG_SIG,\
    CAN_SEND_MSG_SIG,\
    CAN_PASSIVE_ERROR_SIG,\
    CAN_BUS_OFF_SIG,\
    CAN_ERROR_CLEAR_SIG
//$enddecl${OCs::Signals} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${CM::Signals} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CM::Signals::private_signals} ............................................
enum private_signals {
// Publish Subscribe Signals
    TIMEOUT_SIG = Q_USER_SIG,

    // - Only PRIVATE

    MAX_PUB_SIG,

    // COMMON Signals
    RUNNING_QF_SIG,
    INIT_COMPLETE_SIG,

    // CAN OC Signals
    OC_CAN_SIGNALS,

    // IPC OC Signals
    OC_IPC_SIGNALS,

    MAX_PRIVATE_SIG,
};

//${CM::Signals::struct} .....................................................
typedef struct {
    uint16_t const sig_id;
    QActive * const * const p_ao;
}com_ipc_tag_t;

//${CM::Signals::com_signals_ipc_cpu1_cm[COM_SIG_~} ..........................
extern com_ipc_tag_t com_signals_ipc_cpu1_cm[COM_SIG_IPC_CPU1_CM_MAX];

//${CM::Signals::com_signals_ipc_cpu2_cm[COM_SIG_~} ..........................
extern com_ipc_tag_t com_signals_ipc_cpu2_cm[COM_SIG_IPC_CPU2_CM_MAX];
//$enddecl${CM::Signals} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//================================================
//===================Priorities===================
//================================================

//$declare${CM::ao_priority} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CM::ao_priority} .........................................................
enum ao_priority {
    // Priority in ascendance order
    IDLE_TASK=0U,
    AO_COMMUNICATION_PRIO,
};
//$enddecl${CM::ao_priority} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//================================================
//=================Active-Objects=================
//================================================

// AO_Communication
//$declare${CM::AOs::AO_Communication::globals} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CM::AOs::AO_Communication::globals::p_ao_communication} ..................
extern QActive * const p_ao_communication;

//${CM::AOs::AO_Communication::globals::ao_communication_ctor} ...............
void ao_communication_ctor(const QActive  * const pAO);
//$enddecl${CM::AOs::AO_Communication::globals} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//================================================
//=============Orthogonal-Components==============
//================================================

//$declare${CM::OC_enum} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CM::OC_enum::IPC::ipc_named} .............................................
enum ipc_named {
    OC_IPC_CM_CPU1_ID,
    OC_IPC_CM_CPU2_ID,
    OC_IPC_NUM_OF_INST,
};

//${CM::OC_enum::CAN::can_named} .............................................
enum can_named {
    OC_CAN_CANA_ID,
    OC_CAN_MCAN_ID,
    OC_CAN_NUM_OF_INST,
};
//$enddecl${CM::OC_enum} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//================================================
//================Immutable-Events================
//================================================

//$declare${CPU1::Immutable_Events} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CPU1::Immutable_Events::General::im_evt_running_qf} ......................
extern QEvt const im_evt_running_qf;

//${CPU1::Immutable_Events::General::im_evt_init_complete} ...................
extern QEvt const im_evt_init_complete;

//${CPU1::Immutable_Events::FSBB::im_evt_precharge_start} ....................
extern QEvt const im_evt_precharge_start;

//${CPU1::Immutable_Events::FSBB::im_evt_precharge_finish} ...................
extern QEvt const im_evt_precharge_finish;

//${CPU1::Immutable_Events::FSBB::im_evt_start_control} ......................
extern QEvt const im_evt_start_control;

//${CPU1::Immutable_Events::FSBB::im_evt_stop_control} .......................
extern QEvt const im_evt_stop_control;

//${CPU1::Immutable_Events::FSBB::im_evt_il_0} ...............................
extern QEvt const im_evt_il_0;

//${CPU1::Immutable_Events::FSBB::im_evt_reset} ..............................
extern QEvt const im_evt_reset;

//${CPU1::Immutable_Events::Communication::im_evt_ipc_receive_msg[OC_IPC_NU~}
extern OC_Evt const im_evt_ipc_receive_msg[OC_IPC_NUM_OF_INST];

//${CPU1::Immutable_Events::Communication::im_evt_ipc_send_msg[OC_IPC_NUM_O~}
extern OC_Evt const im_evt_ipc_send_msg[OC_IPC_NUM_OF_INST];

//${CPU1::Immutable_Events::Communication::im_evt_ipc_full_bus[OC_IPC_NUM_O~}
extern OC_Evt const im_evt_ipc_full_bus[OC_IPC_NUM_OF_INST];

//${CPU1::Immutable_Events::Communication::im_evt_ipc_reset_ch[OC_IPC_NUM_O~}
extern OC_Evt const im_evt_ipc_reset_ch[OC_IPC_NUM_OF_INST];

//${CPU1::Immutable_Events::Communication::im_evt_ipc_reset_complete[OC_IPC~}
extern OC_Evt const im_evt_ipc_reset_complete[OC_IPC_NUM_OF_INST];

//${CPU1::Immutable_Events::Communication::im_evt_ipc_remote_reset[OC_IPC_N~}
extern OC_Evt const im_evt_ipc_remote_reset[OC_IPC_NUM_OF_INST];
//$enddecl${CPU1::Immutable_Events} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif // MAIN_QM_H_
