//$file${.::Cores_Project::CM::qm_files::main_qm.c} vvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: main_model.qm
// File:  ${.::Cores_Project::CM::qm_files::main_qm.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Cores_Project::CM::qm_files::main_qm.c} ^^^^^^^^^^^^^^^^^^^^^^^
#include "main_qm.h"

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//$enddef${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${CM::Immutable_Events} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${CM::Immutable_Events::General::im_evt_running_qf} ........................
QEvt const im_evt_running_qf = QEVT_INITIALIZER(RUNNING_QF_SIG);

//${CM::Immutable_Events::General::im_evt_init_complete} .....................
QEvt const im_evt_init_complete = QEVT_INITIALIZER(INIT_COMPLETE_SIG);

//${CM::Immutable_Events::Communication::im_evt_ipc_receive_msg[OC_IPC_NU~} ..
OC_Evt const im_evt_ipc_receive_msg[OC_IPC_NUM_OF_INST] ={
    [OC_IPC_CM_CPU1_ID] = {
        .super = QEVT_INITIALIZER(IPC_RECEIVE_MSG_SIG),
        .ID = OC_IPC_CM_CPU1_ID,
    },
    [OC_IPC_CM_CPU2_ID] = {
        .super = QEVT_INITIALIZER(IPC_RECEIVE_MSG_SIG),
        .ID = OC_IPC_CM_CPU2_ID,
    }
};

//${CM::Immutable_Events::Communication::im_evt_ipc_send_msg[OC_IPC_NUM_O~} ..
OC_Evt const im_evt_ipc_send_msg[OC_IPC_NUM_OF_INST] ={
    [OC_IPC_CM_CPU1_ID] = {
        .super = QEVT_INITIALIZER(IPC_SEND_MSG_SIG),
        .ID = OC_IPC_CM_CPU1_ID,
    },
    [OC_IPC_CM_CPU2_ID] = {
        .super = QEVT_INITIALIZER(IPC_SEND_MSG_SIG),
        .ID = OC_IPC_CM_CPU2_ID,
    }
};

//${CM::Immutable_Events::Communication::im_evt_ipc_full_bus[OC_IPC_NUM_O~} ..
OC_Evt const im_evt_ipc_full_bus[OC_IPC_NUM_OF_INST] ={
    [OC_IPC_CM_CPU1_ID] = {
        .super = QEVT_INITIALIZER(IPC_FULL_BUS_SIG),
        .ID = OC_IPC_CM_CPU1_ID,
    },
    [OC_IPC_CM_CPU2_ID] = {
        .super = QEVT_INITIALIZER(IPC_FULL_BUS_SIG),
        .ID = OC_IPC_CM_CPU2_ID,
    }
};

//${CM::Immutable_Events::Communication::im_evt_ipc_reset_ch[OC_IPC_NUM_O~} ..
OC_Evt const im_evt_ipc_reset_ch[OC_IPC_NUM_OF_INST] ={
    [OC_IPC_CM_CPU1_ID] = {
        .super = QEVT_INITIALIZER(IPC_RESET_CH_SIG),
        .ID = OC_IPC_CM_CPU1_ID,
    },
    [OC_IPC_CM_CPU2_ID] = {
        .super = QEVT_INITIALIZER(IPC_RESET_CH_SIG),
        .ID = OC_IPC_CM_CPU2_ID,
    }
};

//${CM::Immutable_Events::Communication::im_evt_ipc_reset_complete[OC_IPC~} ..
OC_Evt const im_evt_ipc_reset_complete[OC_IPC_NUM_OF_INST] ={
    [OC_IPC_CM_CPU1_ID] = {
        .super = QEVT_INITIALIZER(IPC_RESET_COMPLETE_SIG),
        .ID = OC_IPC_CM_CPU1_ID,
    },
    [OC_IPC_CM_CPU2_ID] = {
        .super = QEVT_INITIALIZER(IPC_RESET_COMPLETE_SIG),
        .ID = OC_IPC_CM_CPU2_ID,
    }
};

//${CM::Immutable_Events::Communication::im_evt_ipc_remote_reset[OC_IPC_N~} ..
OC_Evt const im_evt_ipc_remote_reset[OC_IPC_NUM_OF_INST] ={
    [OC_IPC_CM_CPU1_ID] = {
        .super = QEVT_INITIALIZER(IPC_REMOTE_RESET_SIG),
        .ID = OC_IPC_CM_CPU1_ID,
    },
    [OC_IPC_CM_CPU2_ID] = {
        .super = QEVT_INITIALIZER(IPC_REMOTE_RESET_SIG),
        .ID = OC_IPC_CM_CPU2_ID,
    }
};
//$enddef${CM::Immutable_Events} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
