//$file${.::Cores_Project::CPU1::qm_files::OCs::oc_max31865::oc_max31865.h} vv
//
// Model: main_model.qm
// File:  ${.::Cores_Project::CPU1::qm_files::OCs::oc_max31865::oc_max31865.h}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Cores_Project::CPU1::qm_files::OCs::oc_max31865::oc_max31865.h} 
#ifndef OC_MAX31865_H_
#define OC_MAX31865_H_

#include "main_qm.h"

#include "max31865/max31865.h"

//$declare${OCs::OC_MAX31865} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${OCs::OC_MAX31865::OC_MAX31865} ...........................................
typedef struct {
// protected:
    QHsm super;

// private:
    QActive * owner;
    uint16_t id;
    uint16_t chip_select;
    max31865_config_t config;
    QueueHandle_t queue_handler;
    uint16_t queue_storage[10];
    StaticQueue_t queue_buffer;
    uint16_t current_measure_id;
    uint16_t spi_read_status;

// public:
    uint16_t measure_read_id;
    RTD_measure_t measure_read_value;
    uint16_t measure_threshold_fault;

// private:
    OC_TimeEvt oc_time_evt_timeout;
} OC_MAX31865;

// public:
void OC_MAX31865_ctor(OC_MAX31865 * const me,
    QActive * const owner,
    uint16_t id);

// private:
uint16_t OC_MAX31865_local_queue_start(OC_MAX31865 * const me);
uint16_t OC_MAX31865_local_queue_send(OC_MAX31865 * const me,
    uint16_t const *  data);
uint16_t OC_MAX31865_local_queue_receive(OC_MAX31865 * const me,
    uint16_t * const data);
void OC_MAX31865_spi_receive_message(OC_MAX31865 * const me,
    SPI_Message_Response_t spi_message);
void OC_MAX31865_spi_read_request(OC_MAX31865 * const me);
void OC_MAX31865_spi_one_shot_request(OC_MAX31865 * const me,
    uint16_t measure_id);
void OC_MAX31865_max_config(OC_MAX31865 * const me);

// protected:
QState OC_MAX31865_initial(OC_MAX31865 * const me, void const * const par);
QState OC_MAX31865_Waiting_QF(OC_MAX31865 * const me, QEvt const * const e);
QState OC_MAX31865_Start(OC_MAX31865 * const me, QEvt const * const e);
QState OC_MAX31865_Operation(OC_MAX31865 * const me, QEvt const * const e);
QState OC_MAX31865_Waiting_Request(OC_MAX31865 * const me, QEvt const * const e);
QState OC_MAX31865_Waiting_Measure(OC_MAX31865 * const me, QEvt const * const e);
QState OC_MAX31865_Waiting_SPI(OC_MAX31865 * const me, QEvt const * const e);

//${OCs::OC_MAX31865::mux_select} ............................................
enum mux_select {
    OC_MAX31865_MUX0 = 0U,
    OC_MAX31865_MUX1 = 1U,
    OC_MAX31865_MUX2 = 2U,
    OC_MAX31865_MUX3 = 3U,
    OC_MAX31865_NUM_OF_MUX,
};
//$enddecl${OCs::OC_MAX31865} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
