//$file${.::Cores_Project::CPU1::qm_files::OCs::oc_max31865::oc_max31865.c} vv
//
// Model: main_model.qm
// File:  ${.::Cores_Project::CPU1::qm_files::OCs::oc_max31865::oc_max31865.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Cores_Project::CPU1::qm_files::OCs::oc_max31865::oc_max31865.c} 
#include "./oc_max31865.h"

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${OCs::OC_MAX31865} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${OCs::OC_MAX31865::OC_MAX31865} ...........................................

//${OCs::OC_MAX31865::OC_MAX31865::ctor} .....................................
void OC_MAX31865_ctor(OC_MAX31865 * const me,
    QActive * const owner,
    uint16_t id)
{
    QHsm_ctor(&me->super, Q_STATE_CAST(&OC_MAX31865_initial));
    me->owner = owner;
    me->id = id;

    QTimeEvt_ctorX(&me->oc_time_evt_timeout.super, me->owner, MAX31865_TIMEOUT_SIG, 0U);
    me->oc_time_evt_timeout.ID = id;
}

//${OCs::OC_MAX31865::OC_MAX31865::SM} .......................................
QState OC_MAX31865_initial(OC_MAX31865 * const me, void const * const par) {
    //${OCs::OC_MAX31865::OC_MAX31865::SM::initial}
    return Q_TRAN(&OC_MAX31865_Waiting_QF);
}

//${OCs::OC_MAX31865::OC_MAX31865::SM::Waiting_QF} ...........................
QState OC_MAX31865_Waiting_QF(OC_MAX31865 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Waiting_QF::RUNNING_QF}
        case RUNNING_QF_SIG: {
            status_ = Q_TRAN(&OC_MAX31865_Start);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${OCs::OC_MAX31865::OC_MAX31865::SM::Start} ................................
QState OC_MAX31865_Start(OC_MAX31865 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Start}
        case Q_ENTRY_SIG: {
            OC_MAX31865_local_queue_start(me);
            status_ = Q_HANDLED();
            break;
        }
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Start::INIT_COMPLETE}
        case INIT_COMPLETE_SIG: {
            status_ = Q_TRAN(&OC_MAX31865_Operation);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${OCs::OC_MAX31865::OC_MAX31865::SM::Operation} ............................
QState OC_MAX31865_Operation(OC_MAX31865 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::initial}
        case Q_INIT_SIG: {
            //BSP_BKPT;
            OC_MAX31865_max_config(me);
            status_ = Q_TRAN(&OC_MAX31865_Waiting_Request);
            break;
        }
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::MAX31865_SPI_RESPONSE}
        case MAX31865_SPI_RESPONSE_SIG: {
            //BSP_BKPT;
            status_ = Q_HANDLED();
            break;
        }
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::MAX31865_REQUEST_TEMPERATURE}
        case MAX31865_REQUEST_TEMPERATURE_SIG: {
            OC_Evt_MAX31865_Temperature_Request_t const * message = Q_EVT_CAST(OC_Evt_MAX31865_Temperature_Request_t);
            OC_MAX31865_local_queue_send(me, &(message->temperature_id) );
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_Request} ...........
QState OC_MAX31865_Waiting_Request(OC_MAX31865 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_Request}
        case Q_ENTRY_SIG: {
            //BSP_BKPT;
            status_ = Q_HANDLED();
            break;
        }
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_Request::MAX31865_REQUEST_TEMPERATURE}
        case MAX31865_REQUEST_TEMPERATURE_SIG: {
            BSP_BKPT;

            OC_Evt_MAX31865_Temperature_Request_t const * message = Q_EVT_CAST(OC_Evt_MAX31865_Temperature_Request_t);
            OC_MAX31865_spi_one_shot_request(
                me,
                message->temperature_id
            );
            status_ = Q_TRAN(&OC_MAX31865_Waiting_Measure);
            break;
        }
        default: {
            status_ = Q_SUPER(&OC_MAX31865_Operation);
            break;
        }
    }
    return status_;
}

//${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_Measure} ...........
QState OC_MAX31865_Waiting_Measure(OC_MAX31865 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_Measure}
        case Q_ENTRY_SIG: {
            BSP_BKPT;
            QTimeEvt_armX(
                &me->oc_time_evt_timeout.super,
                (uint16_t) ((MEASURE_TEMPERATURE_TIMEOUT_PERIOD_MS)/(RTOS_TICK_PERIOD_MS)),
                (uint16_t) ((MEASURE_TEMPERATURE_TIMEOUT_PERIOD_MS)/(RTOS_TICK_PERIOD_MS))
            );
            status_ = Q_HANDLED();
            break;
        }
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_Measure}
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->oc_time_evt_timeout.super);
            status_ = Q_HANDLED();
            break;
        }
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_Measure::MAX31865_READ_FINISH}
        case MAX31865_READ_FINISH_SIG: {
            BSP_BKPT;

            me->measure_read_value.data = 0;

            OC_MAX31865_spi_read_request(
                me
            );
            status_ = Q_TRAN(&OC_MAX31865_Waiting_SPI);
            break;
        }
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_Measure::MAX31865_TIMEOUT}
        case MAX31865_TIMEOUT_SIG: {
            BSP_BKPT;

            // Clear Interrupt
            me->spi_read_status = 0;
            OC_MAX31865_spi_read_request(
                me
            );

            // Request Another Measure
            OC_MAX31865_spi_one_shot_request(
                me,
                me->current_measure_id
            );

            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&OC_MAX31865_Operation);
            break;
        }
    }
    return status_;
}

//${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_SPI} ...............
QState OC_MAX31865_Waiting_SPI(OC_MAX31865 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_SPI}
        case Q_ENTRY_SIG: {
            BSP_BKPT;

            QTimeEvt_armX(
                &me->oc_time_evt_timeout.super,
                (uint16_t) ((MEASURE_TEMPERATURE_TIMEOUT_PERIOD_MS)/(RTOS_TICK_PERIOD_MS)),
                (uint16_t) ((MEASURE_TEMPERATURE_TIMEOUT_PERIOD_MS)/(RTOS_TICK_PERIOD_MS))
            );
            status_ = Q_HANDLED();
            break;
        }
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_SPI}
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->oc_time_evt_timeout.super);
            status_ = Q_HANDLED();
            break;
        }
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_SPI::MAX31865_SPI_READ_FINISH}
        case MAX31865_SPI_READ_FINISH_SIG: {
            //BSP_BKPT;

            me->spi_read_status = 0;
            me->measure_read_id = me->current_measure_id;
            //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_SPI::MAX31865_SPI_REA~::[//ReadFromQueueOC_MAX31865_loca~}
            if (// Read From Queue
                OC_MAX31865_local_queue_receive( me , &me->current_measure_id ))
            {
                //BSP_BKPT;
                OC_MAX31865_spi_one_shot_request(
                    me,
                    me->current_measure_id
                );

                status_ = Q_TRAN(&OC_MAX31865_Waiting_Measure);
            }
            //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_SPI::MAX31865_SPI_REA~::[else]}
            else {
                status_ = Q_TRAN(&OC_MAX31865_Waiting_Request);
            }
            break;
        }
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_SPI::MAX31865_SPI_RESPONSE}
        case MAX31865_SPI_RESPONSE_SIG: {
            OC_Evt_SPI_Message_Response_t const * response = Q_EVT_CAST(OC_Evt_SPI_Message_Response_t);

            OC_MAX31865_spi_receive_message(
                me,
                response->response
            );

            if(me->spi_read_status == 0b11){
                QACTIVE_POST( me->owner , &im_evt_max31865_spi_read_finish[me->id].super , (void *)0);
            }
            status_ = Q_HANDLED();
            break;
        }
        //${OCs::OC_MAX31865::OC_MAX31865::SM::Operation::Waiting_SPI::MAX31865_TIMEOUT}
        case MAX31865_TIMEOUT_SIG: {
            // Request Another Reading
            OC_MAX31865_spi_read_request(
                me
            );
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&OC_MAX31865_Operation);
            break;
        }
    }
    return status_;
}
//$enddef${OCs::OC_MAX31865} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
